<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-catalogsale-products">
<div class="page-title category-title">
    <h1><?php echo $this->__('Specials') ?></h1>
</div>
    <?php $suffix = $this->getNameInLayout(); ?>
    <ul class="products-grid row" id="widget-catalogsale-products-<?php echo $suffix; ?>">
    <?php foreach ($_products->getItems() as $_product): ?>
        <li class="item col-xs-12 col-sm-3">
            <div class="grid_wrap">
            <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(228) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
            <div class="product-shop">
                    <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                        <div class="desc_grid">
                            <?php/* 
                            $small_getDescription = strip_tags($_product->getShortDescription());
                     if (strlen($small_getDescription) < 70) echo($small_getDescription);
                     else { echo mb_substr($small_getDescription, 0, 70,'UTF-8').'...';}*/ ?></div>
                        <?php if(Mage::getSingleton('customer/session')->isLoggedIn()) { echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix); }?>


                 <div class="actions cartform">
                    <?php if($_product->isSaleable()): ?>
                     <?php if(Mage::getSingleton('customer/session')->isLoggedIn()) { ?>
                        <form class="product_addtocart_form" action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId()?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                        <?php if(!$_product->isGrouped()): ?>
                                                   <label for="qty" class="qtylabel"><?php echo $this->__('Qty') ?>:</label>
                        <input type="text" class="form-control qtybox" name="qty">
                        <?php endif; ?>
                        <button type="submit" class="link_cart"><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></button>
                        </form>
                     <?php } ?>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <a style="line-height: 40px; margin-left: 10px;" href="<?php echo $_product->getProductUrl() ?>" class="link_details"><?php echo $this->__('Details') ?></a>
                </div>
            </div>
              <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                <div class="label-product">             
                    <?php if($_product->getData('new')){echo '<span class="new"><strong>'.$this->__('New').'</strong></span>';  }?>
                    <?php if($_product->getData('sale')){echo '<span class="sale"><strong>'.$this->__('Sale').'</strong></span>';  }?>
                </div>
                </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('widget-catalogsale-products-<?php echo $suffix; ?>', 'none-recursive')</script>
</div>
<?php endif; ?>
