<?php
$_fieldsContainerId = 'order-shipping_address_fields';
$_countries = Mage::getResourceModel('directory/country_collection')
    ->loadData()
    ->toOptionArray(false);

$params = $this->getRequest()->getParams();
if (isset($params['order_id'])) {
    $order = Mage::getModel('sales/order')->load($params['order_id']);
    $shippingAddress = $order->getShippingAddress();
    $billingAddress = $order->getBillingAddress();
    if (!empty($shippingAddress)) {
        $shippingInfo = $order->getShippingAddress()->getData();
    }
    if (!empty($billingAddress)) {
        $billingInfo = $billingAddress->getData();
    }
    $customer = Mage::getModel('customer/customer')->load($order['customer_id'])->getData();
}

?>

<!--change customer default-->
<?php
$customerDefaultToChange = Mage::getModel('xpos/guest')->getDefaultCustomer();
//?>
<ul id="ul_change_customer_guest" style="display: none">
    <li style="display: none;" id="change_customer_guest"
        street_line="<?php echo $this->helper('customer/address')->getStreetLines() ?>"
        id_customer="<?php echo $customerDefaultToChange['account']['id'] ?>"
        type="<?php echo $customerDefaultToChange['account']['type'] ?>"
        shipping_telephone="<?php echo $customerDefaultToChange['shipping_address']['telephone'] ?>"
        shipping_postcode="<?php echo $customerDefaultToChange['shipping_address']['postcode'] ?>"
        shipping_outofcityarea="<?php echo $customerDefaultToChange['shipping_address']['outofcityarea'] ?>"
        shipping_region_id="<?php echo $customerDefaultToChange['shipping_address']['region_id'] ?>"
        shipping_region="<?php echo $customerDefaultToChange['shipping_address']['region'] ?>"
        shipping_country_id="<?php echo $customerDefaultToChange['shipping_address']['country_id'] ?>"
        shipping_street="<?php echo $customerDefaultToChange['shipping_address']['street'] ?>"
        shipping_city="<?php echo $customerDefaultToChange['shipping_address']['city'] ?>"
        shipping_statecounty="<?php echo $customerDefaultToChange['shipping_address']['statecounty'] ?>"
        shipping_company="<?php echo $customerDefaultToChange['shipping_address']['company'] ?>"
        shipping_lastname="<?php echo $customerDefaultToChange['shipping_address']['lastname'] ?>"
        shipping_firstname="<?php echo $customerDefaultToChange['shipping_address']['firstname'] ?>"
        billing_telephone="<?php echo $customerDefaultToChange['billing_address']['telephone'] ?>"
        billing_city="<?php echo $customerDefaultToChange['billing_address']['city'] ?>"
        billing_statecounty="<?php echo $customerDefaultToChange['billing_address']['statecounty'] ?>"
        billing_company="<?php echo $customerDefaultToChange['billing_address']['company'] ?>"
        billing_outofcityarea="<?php echo $customerDefaultToChange['billing_address']['outofcityarea'] ?>"
        billing_country_id="<?php echo $customerDefaultToChange['billing_address']['country_id'] ?>"
        billing_postcode="<?php echo $customerDefaultToChange['billing_address']['postcode'] ?>"
        billing_region_id="<?php echo $customerDefaultToChange['billing_address']['region_id'] ?>"
        billing_region="<?php echo $customerDefaultToChange['billing_address']['region'] ?>"
        billing_street="<?php echo $customerDefaultToChange['billing_address']['street'] ?>"
        city="<?php echo $customerDefaultToChange['shipping_address']['city'] ?>"
        statecounty="<?php echo $customerDefaultToChange['shipping_address']['statecounty'] ?>"
        company="<?php echo $customerDefaultToChange['shipping_address']['company'] ?>"
        outofcityarea="<?php echo $customerDefaultToChange['shipping_address']['outofcityarea'] ?>"
        country_id="<?php echo $customerDefaultToChange['shipping_address']['country_id'] ?>"
        postcode="<?php echo $customerDefaultToChange['shipping_address']['postcode'] ?>"
        region_id="<?php echo $customerDefaultToChange['shipping_address']['region_id'] ?>"
        region="<?php echo $customerDefaultToChange['shipping_address']['region'] ?>"
        street="<?php echo $customerDefaultToChange['shipping_address']['street'][0] ?>"
        lastname="<?php echo $customerDefaultToChange['shipping_address']['lastname'] ?>"
        firstname="<?php echo $customerDefaultToChange['shipping_address']['firstname'] ?>"
        telephone="<?php echo $customerDefaultToChange['shipping_address']['telephone'] ?>"
        email="<?php echo $customerDefaultToChange['account']['email'] ?>" desc=""
        name="<?php echo $customerDefaultToChange['shipping_address']['firstname'] . ' ' . $customerDefaultToChange['shipping_address']['lastname'] ?>"
        label="<?php echo($customerDefaultToChange['shipping_address']['firstname'] . $customerDefaultToChange['shipping_address']['lastname'] . $customerDefaultToChange['shipping_address']['telephone'] . $customerDefaultToChange['account']['email']) ?>"
        onclick="getCustomerSelectionId(this)"></li>
</ul>
<!--end change customer default-->

<input type="hidden" name="order[account][group_id]" id="customer_group"
       value="<?php if (isset($order['customer_id'])) {
           echo $customer['group_id'];
       } else {
           echo 1;
       } ?>"/>
<input type="hidden" name="order[account][type]" id="customer_type" value="<?php if (isset($order['customer_id'])) {
    echo "exist";
} else {
    echo "guest";
} ?>"/>

<div id="customer_account_fields">

    <!-- billing address-->
    <div class="box-left" style="margin-top: 7px; display:none;" id="billing-details">
        <fieldset class="np">
            <input type="checkbox" id="order-billing_same_as_billing" name="billing_same_as_billing"
                   onchange="enableBilling(this);" value="1" checked="checked"/>
            <label for="order-billing_same_as_billing"
                   class="no-float"><?php echo $this->__("Billing Address") ?></label>

            <div class="order-address" id="billing-<?php echo $_fieldsContainerId ?>">
                <div class="content" id="order-billing-address-content" style="display: none; position: relative;">
                    <div style="position:absolute; width: 100%; height:100%; top:0; left:0;display:block;"
                         id="billing-overlay">&nbsp;</div>
                    <select id="customer_billing_address_list" style="width:97.5%;"
                            onchange="switchBillingAddress(this)">
                    </select>

                    <p><a href="#clear" id="clear_billing_address"><?php echo $this->__("Clear") ?></a></p>
                    <input name="order[billing_address][firstname]" type="text"
                           placeholder="<?php echo $this->__('First Name'); ?>"
                           class="input-text block notrequired-entry"
                           id="order-billing_address_address_firstname"
                           value="<?php echo isset($billingInfo['firstname']) ? $billingInfo['firstname'] : ''; ?>">
                    <input name="order[account][gender]" type="hidden" value="123">
                    </input>


                    <input id="order-billing_address_address_lastname" name="order[billing_address][lastname]"
                           type="text"
                           placeholder="<?php echo $this->__('Last Name'); ?>"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($billingInfo['lastname']) ? $billingInfo['lastname'] : ''; ?>">

                    <input id="order-billing_address_address_company" name="order[billing_address][company]"
                           type="text"
                           placeholder="<?php echo $this->__('Company'); ?>"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($billingInfo['company']) ? $billingInfo['company'] : ''; ?>">

                    <input id="order-billing_address_address_street0" name="order[billing_address][street][0]"
                           type="text"
                           placeholder="<?php echo $this->__('Street'); ?>"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($billingInfo['street']) ? $billingInfo['street'] : ''; ?>">

                    <select id="order-billing_address_address_country_id" class=" notrequired-entry select"
                            name="order[billing_address][country_id]" id="order-billing_address_country_id"
                            onChange="clearBillingRegion()">

                        <?php if (count($_countries) > 0): ?>
                            <option value="">-- Please Select --</option>
                            <?php foreach ($_countries as $_country): ?>
                                <option
                                    value="<?php echo $_country['value'] ?>" <?php if ($_country['value'] == (isset($billingInfo['country_id']) ? $billingInfo['country_id'] : '')): ?> selected <?php endif ?>>
                                    <?php echo $_country['label'] ?>
                                </option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>

                    <select id="order-billing_address_address_region_id" onchange="getcountybill(this)"
                            name="order[billing_address][region_id]"
                            title="<?php echo $this->__('State/Province') ?>" class="validate-select"
                            style="display:none;max-width: 108px;"
                        >
                        <option value="0"><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>

                    <select id="order-billing_address_address_region_virtual" onchange="updateBillingVirtual();"
                            name="order[billing_address][region_virtual]"
                            title="<?php echo $this->__('State/Province') ?>"
                            class="validate-select" style="display:none;">
                    </select>

                    <input id="order-billing_address_address_region" name="order[billing_address][region]"
                           type="text"
                           style="display: none !important;max-width: 108px;"
                           placeholder="<?php echo $this->__('Region'); ?>"
                           class="input-text notrequired-entry"
                           value="<?php echo isset($billingInfo['region']) ? $billingInfo['region'] : ''; ?>">

                    <input id="order-billing_address_address_statecounty" name="order[billing_address][statecounty]"
                           placeholder="<?php echo $this->__('County'); ?>"
                           type="text"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($billingInfo['statecounty']) ? $billingInfo['statecounty'] : ''; ?>">

                    <input id="order-billing_address_address_city" name="order[billing_address][city]"
                           placeholder="<?php echo $this->__('City'); ?>"
                           type="text"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($billingInfo['city']) ? $billingInfo['city'] : ''; ?>">

                    <input id="order-billing_address_address_postcode" name="order[billing_address][postcode]"
                           type="text"
                           placeholder="<?php echo $this->__('Post Code'); ?>"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($billingInfo['postcode']) ? $billingInfo['postcode'] : ''; ?>">

                    <input id="order-billing_address_address_outofcityarea" name="order[billing_address][outofcityarea]"
                           placeholder="<?php echo $this->__('Outofcityarea'); ?>"
                           type="text"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($billingInfo['outofcityarea']) ? $billingInfo['outofcityarea'] : ''; ?>">

                    <input id="order-billing_address_address_telephone"
                           placeholder="<?php echo $this->__('Telephone'); ?>"
                           name="order[billing_address][telephone]" type="text"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($billingInfo['telephone']) ? $billingInfo['telephone'] : ''; ?>">

                    <!-- This strict the region load event -->
                    <label class="required">
                        <span class="required"></span>
                    </label>

                    <div class="action">
                        <button type="button" class="smart-btn" id=""
                                onclick="jQuery('#copy-from-billing-address').click()"><?php echo $this->__('Set as Shipping'); ?></button>
                        <button type="button" class="smart-btn" id=""
                                onclick="change_new_customer()"><?php echo $this->__('Register'); ?></button>
                    </div>
                </div>
            </div>

        </fieldset>
    </div>
    <!--End billing address-->

    <!--Shipping address-->
    <div class="box-right" style=" margin-top: 7px;" id="shipping-details">
        <fieldset class="np">
            <input type="checkbox" id="order-shipping_same_as_billing" name="shipping_same_as_billing"
                   onchange="enableShipping(this);" checked/>
            <label for="order-shipping_same_as_billing"
                   class="no-float"><?php echo $this->__('Shipping Address'); ?></label>

            <div class="order-address" id="<?php echo $_fieldsContainerId ?>">
                <div class="content" id="order-address-content" style="display: none;position: relative;">
                    <div style="position:absolute; width: 100%; height:100%; top:0; left:0;display:block;"
                         id="shipping-overlay">&nbsp;</div>
                    <select id="customer_shipping_address_list" style="width:97.5%;"
                            onchange="switchShippingAddress(this)">
                    </select>

                    <p><a href="#copy-from-billing"
                          id="copy-from-billing-address"><?php echo $this->__('Same as'); ?></a> | <a
                            href="#clear" id="clear_shipping_address"><?php echo $this->__('Clear'); ?></a></p>
                    <div id="update-customer-address-message"></div>
                    <input name="order[shipping_address][id]" type="hidden"
                           id="order-shipping_address_address_id"
                           />

                    <input name="order[shipping_address][salestaxid]" type="text"
                           placeholder="<?php echo $this->__('Sales Tax ID'); ?>"
                           class="input-text block notrequired-entry"
                           id="order-shipping_address_address_salestaxid"
                           value="<?php echo isset($shippingInfo['salestaxid']) ? $shippingInfo['salestaxid'] : ''; ?>">

                    <input name="order[shipping_address][entityname]" type="text"
                           placeholder="<?php echo $this->__('Entity name'); ?>"
                           class="input-text block notrequired-entry"
                           id="order-shipping_address_address_entityname"
                           value="<?php echo isset($shippingInfo['entityname']) ? $shippingInfo['entityname'] : ''; ?>">

                    <input name="order[shipping_address][firstname]" type="hidden"
                           placeholder="<?php echo $this->__('First Name'); ?>"
                           class="input-text block notrequired-entry"
                           id="order-shipping_address_address_firstname"
                           value="<?php echo isset($shippingInfo['firstname']) ? $shippingInfo['firstname'] : ''; ?>">
                    <input id="order-shipping_address_address_lastname" name="order[shipping_address][lastname]"
                           placeholder="<?php echo $this->__('Last Name'); ?>"
                           type="hidden"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($shippingInfo['lastname']) ? $shippingInfo['lastname'] : ''; ?>">

                    <input id="order-shipping_address_address_company" name="order[shipping_address][company]"
                           placeholder="<?php echo $this->__('Company'); ?>"
                           type="text"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($shippingInfo['company']) ? $shippingInfo['company'] : ''; ?>">

                    <input id="order-shipping_address_address_street0" name="order[shipping_address][street][0]"
                           placeholder="<?php echo $this->__('Street'); ?>"
                           type="text"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($shippingInfo['street']) ? $shippingInfo['street'] : ''; ?>">

                    <select id="order-shipping_address_address_country_id" class=" notrequired-entry select"
                            name="order[shipping_address][country_id]" id="order-shipping_address_country_id"
                            onChange="clearShippingRegion()">

                        <?php if (count($_countries) > 0): ?>
                            <option value="">-- Please Select --</option>
                            <?php foreach ($_countries as $_country): ?>
                                <option
                                    value="<?php echo $_country['value'] ?>" <?php if ($_country['value'] == (isset($shippingInfo['country_id']) ? $shippingInfo['country_id'] : '')): ?> selected <?php endif ?>>
                                    <?php echo $_country['label'] ?>
                                </option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>

                    <select id="order-shipping_address_address_region_id" onchange="getcountyship(this)"
                            name="order[shipping_address][region_id]"
                            title="<?php echo $this->__('State/Province') ?>" class="validate-select"
                            style="display:none;"
                        >
                        <option value="0"><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>

                    <select id="order-shipping_address_address_region_virtual" onchange="updateVirtual();"
                            name="order[shipping_address][region_virtual]"
                            title="<?php echo $this->__('State/Province') ?>"
                            class="validate-select" style="display:none;">
                    </select>

                    <input id="order-shipping_address_address_region" name="order[shipping_address][region]"
                           type="text"
                           style="display:none  !important;max-width: 108px; "
                           placeholder="<?php echo $this->__('Region'); ?>"
                           class="input-text notrequired-entry"
                           value="<?php echo isset($shippingInfo['region']) ? $shippingInfo['region'] : ''; ?>">

                    <input id="order-shipping_address_address_statecounty" name="order[shipping_address][statecounty]"
                           type="text"
                           placeholder="<?php echo $this->__('County'); ?>"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($shippingInfo['statecounty']) ? $shippingInfo['statecounty'] : ''; ?>">

                    <input id="order-shipping_address_address_city" name="order[shipping_address][city]"
                           type="text"
                           placeholder="<?php echo $this->__('City'); ?>"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($shippingInfo['city']) ? $shippingInfo['city'] : ''; ?>">

                    <input id="order-shipping_address_address_postcode" name="order[shipping_address][postcode]"
                           type="text"
                           placeholder="<?php echo $this->__('Post code'); ?>"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($shippingInfo['postcode']) ? $shippingInfo['postcode'] : ''; ?>">

                    <input id="order-shipping_address_address_outofcityarea"
                           name="order[shipping_address][outofcityarea]"
                           type="text"
                           placeholder="<?php echo $this->__('Outofcityarea'); ?>"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($shippingInfo['outofcityarea']) ? $shippingInfo['outofcityarea'] : ''; ?>">

                    <input id="order-shipping_address_address_telephone"
                           placeholder="<?php echo $this->__('Telephone'); ?>"
                           name="order[shipping_address][telephone]" type="text"
                           class="input-text block notrequired-entry"
                           value="<?php echo isset($shippingInfo['telephone']) ? $shippingInfo['telephone'] : ''; ?>">

                    <!-- This strict the region load event -->
                    <label class="required">
                        <span class="required"></span>
                    </label>

                    <div class="action">
                        <button type="button" class="smart-btn" id=""
                                onclick="change_new_customer()"><?php echo $this->__('Register'); ?></button>
                        <button type="button" class="smart-btn" id="update-customer-address" style="display: none"
                                onclick="update_customer_address()"><?php echo $this->__('Update'); ?></button>
                    </div>
                </div>
            </div>

        </fieldset>

    </div>
    <div class="clear"></div>
    <!--End shipping address-->

</div>

<script type="text/javascript">

    var guest_defaultname = '<?php echo Mage::getStoreConfig('xpos/guest/guest_name') ?>';
    guest_defaultname = guest_defaultname.split(" ");
    var guest_firstname = guest_defaultname[0];
    var guest_lastname = '';
    for (var i = 1; i < guest_defaultname.length; i++) {
        guest_lastname = guest_lastname + " " + guest_defaultname[i];
    }
    guest_lastname = jQuery.trim(guest_lastname);
    if (guest_lastname == '') {
        guest_lastname = 'Guest';
    }

    var defaultAddress = {
        'firstname': document.getElementById('change_customer_guest').getAttribute('firstname'),
        'lastname': document.getElementById('change_customer_guest').getAttribute('lastname'),
        'street': document.getElementById('change_customer_guest').getAttribute('street'),
        'billing_street': document.getElementById('change_customer_guest').getAttribute('billing_street'),
        'city': document.getElementById('change_customer_guest').getAttribute('city'),
        'statecounty': document.getElementById('change_customer_guest').getAttribute('statecounty'),
        'outofcityarea': document.getElementById('change_customer_guest').getAttribute('outofcityarea'),
        'country_id': document.getElementById('change_customer_guest').getAttribute('country_id'),
        'billing_company': document.getElementById('change_customer_guest').getAttribute('billing_company'),
        'region': document.getElementById('change_customer_guest').getAttribute('region'),
        'region_id': document.getElementById('change_customer_guest').getAttribute('billing_region_id'),
        'postcode': document.getElementById('change_customer_guest').getAttribute('postcode'),
        'telephone': document.getElementById('change_customer_guest').getAttribute('telephone'),

        'shipping_firstname': document.getElementById('change_customer_guest').getAttribute('shipping_firstname'),
        'shipping_lastname': document.getElementById('change_customer_guest').getAttribute('shipping_lastname'),
        'shipping_city': document.getElementById('change_customer_guest').getAttribute('shipping_city'),
        'shipping_statecounty': document.getElementById('change_customer_guest').getAttribute('shipping_statecounty'),
        'shipping_company': document.getElementById('change_customer_guest').getAttribute('shipping_company'),
        'shipping_outofcityarea': document.getElementById('change_customer_guest').getAttribute('shipping_outofcityarea'),
        'shipping_street': document.getElementById('change_customer_guest').getAttribute('shipping_street'),
        'shipping_country_id': document.getElementById('change_customer_guest').getAttribute('shipping_country_id'),
        'shipping_region': document.getElementById('change_customer_guest').getAttribute('shipping_region'),
        'shipping_region_id': document.getElementById('change_customer_guest').getAttribute('shipping_region_id'),
        'shipping_postcode': document.getElementById('change_customer_guest').getAttribute('shipping_postcode'),
        'shipping_telephone': document.getElementById('change_customer_guest').getAttribute('shipping_telephone')
    };

    var existAddress = defaultAddress;
    function passAddress(addressCusCount, data, tag) {
        tag.empty();
        tag.append(jQuery('<option>', {
            value: -1,
            text: "Add new"
        }));
        for (var i = 0; i < addressCusCount; i++) {
            tag.append(jQuery('<option>', {
                value: i,
                text: data[i].street
            }));
            var optionTag = '#' + tag.attr('id') + ' option[value=' + i + ']';
            jQuery(optionTag)
                .attr('firstname', data[i].firstname)
                .attr('lastname', data[i].lastname)
                .attr('street', data[i].street)
                .attr('city', data[i].city)
                .attr('country_id', data[i].country_id)
                .attr('region', data[i].region)
                .attr('region_id', data[i].region_id)
                .attr('postcode', data[i].postcode)
                .attr('telephone', data[i].telephone)
                .attr('statecounty', data[i].statecounty)
                .attr('outofcityarea', data[i].outofcityarea)
                .attr('company', data[i].company)
                .attr('salestaxid', data[i].salestaxid)
                .attr('entityname', data[i].entityname)
                .attr('address_id', data[i].address_id)
            ;
        }
    }
    function setAdd(arr, update) {
        //alert(JSON.stringify(arr));
        if (jQuery('input[name="order[account][type]"]').val() == 'new' || jQuery('input[name="order[account][type]"]').val() == 'guest' || true) {
            var addressCusCount = arr.addressCusCount;

            var company = '';
            var outofCity = 9;

            var selectBilling = jQuery('#customer_billing_address_list');
            var selectShipping = jQuery('#customer_shipping_address_list');
            passAddress(addressCusCount, arr, selectBilling);
            passAddress(addressCusCount, arr, selectShipping);
            jQuery('#order-shipping_address_address_firstname').val(arr.shipping_firstname);
            jQuery('#order-shipping_address_address_salestaxid').val(arr.salestaxid);
            jQuery('#order-shipping_address_address_entityname').val(arr.entityname);

            jQuery('#order-shipping_address_address_lastname').val(arr.shipping_lastname);
            jQuery('#order-shipping_address_address_street0').val(arr.shipping_street);
            jQuery('#order-shipping_address_address_country_id').val(arr.shipping_country_id);
            jQuery('#order-shipping_address_address_city').val(arr.shipping_city);
            jQuery('#order-shipping_address_address_statecounty').val(arr.shipping_statecounty);

            jQuery('#order-shipping_address_address_company').val(arr.shipping_company);
            jQuery('#order-shipping_address_address_outofcityarea').val(arr.shipping_outofcityarea);
            jQuery('#order-shipping_address_address_region').val(arr.shipping_region);
            jQuery('#order-shipping_address_address_region_id').val(arr.shipping_region_id);
            jQuery('#order-shipping_address_address_postcode').val(arr.shipping_postcode);
            jQuery('#order-shipping_address_address_telephone').val(arr.shipping_telephone);

            jQuery("#entity_name").html(arr.entityname);
            jQuery("#company_name").html(arr.shipping_company);
            jQuery("#sale_tax_id").html(arr.salestaxid);
            jQuery("#county_name").html(arr.shipping_statecounty);
            jQuery("#city_limit").html(arr.shipping_outofcityarea == 10 ? 'Yes' : 'No' );

            jQuery("#entity_name").attr('title',arr.entityname);
            jQuery("#company_name").attr('title',arr.shipping_company);
            jQuery("#sale_tax_id").attr('title',arr.salestaxid);
            jQuery("#county_name").attr('title',arr.shipping_statecounty);
            jQuery("#city_limit").attr('title',arr.shipping_outofcityarea == 10 ? 'Yes' : 'No' );

            jQuery("#customer_selected_street").html(arr.shipping_street ? arr.shipping_street + ',' : '');
            jQuery("#customer_selected_city").html(arr.shipping_city ? arr.shipping_city + ',' : '');
            jQuery("#customer_selected_state").html(arr.shipping_region ? arr.shipping_region + ',' : '');
            jQuery("#customer_selected_zipcode").html(arr.shipping_postcode ? arr.shipping_postcode : '');

            var select_shipping_city = '' +
                '<option value="' + arr.shipping_city
                + '">' + arr.shipping_city + '</option>';
            jQuery('#order-shipping_address_address_city').empty();
            jQuery('#order-shipping_address_address_city').append(select_shipping_city);
            jQuery('#order-shipping_address_address_city').val(arr.shipping_city);
            shippingRegionUpdater.update();

            setTimeout(function () {
                jQuery.uniform.update()
                if (jQuery('#order-shipping_address_address_region_id').is(":disabled")) {
                    jQuery('#uniform-order-shipping_address_address_region_id').hide('slow');
                } else {
                    jQuery('#uniform-order-shipping_address_address_region_id').show('slow');
                }
            }, 10);

            jQuery('#order-billing_address_address_firstname').val(arr.firstname);
            jQuery('#order-billing_address_address_lastname').val(arr.lastname);
            jQuery('#order-billing_address_address_street0').val(arr.billing_street);
            jQuery('#order-billing_address_address_country_id').val(arr.country_id);
            var select_city = '' +
                '<option selected value="' + arr.city
                + '">' + arr.city + '</option>';
            jQuery('#order-billing_address_address_city').empty();
            jQuery('#order-billing_address_address_city').append(select_city);
            jQuery('#order-billing_address_address_city').val(arr.city);

            var bil = arr.billing_statecounty;
            if(arr.billing_statecounty == undefined){
                bil = arr.statecounty;
            }
            jQuery('#order-billing_address_address_statecounty').val(bil);

            var bilcomp = arr.billing_company;
            if(arr.billing_company == undefined){
                bilcomp = arr.company;
            }

            var outofcityarea = arr.billing_outofcityarea;
            if(arr.billing_outofcityarea == undefined){
                outofcityarea = arr.outofcityarea;
            }

            jQuery('#order-billing_address_address_company').val(bilcomp);
            jQuery('#order-billing_address_address_outofcityarea').val(outofcityarea);
            jQuery('#order-billing_address_address_region').val(arr.region);
            jQuery('#order-billing_address_address_region_id').val(arr.region_id);
            jQuery('#order-billing_address_address_postcode').val(arr.postcode);
            jQuery('#order-billing_address_address_telephone').val(arr.telephone);
            billingRegionUpdater.update();

            setTimeout(function () {
                jQuery.uniform.update()
                if (jQuery('#order-billing_address_address_region_id').is(":disabled")) {
                    jQuery('#uniform-order-billing_address_address_region_id').hide('slow');
                } else {
                    jQuery('#uniform-order-billing_address_address_region_id').show('slow');
                }
            }, 10);
        }
        if (update && flag_reload_page) {
            updateShippingRates();
        }
    }

    function changeAddress() {
        var newAddress = {
            'firstname': jQuery('#order-shipping_address_address_firstname').val() != '' ? jQuery('#order-shipping_address_address_firstname').val() : 'Guest',
            'lastname': jQuery('#order-shipping_address_address_lastname').val() != '' ? jQuery('#order-shipping_address_address_lastname').val() : 'Guest',
            'street': jQuery('#order-shipping_address_address_street0').val() != '' ? jQuery('#order-shipping_address_address_street0').val() : '<?php echo Mage::getStoreConfig('xpos/guest/guest_street') ?>',
            'city': jQuery('#order-shipping_address_address_city').val() != '' ? jQuery('#order-shipping_address_address_city').val() : '<?php echo Mage::getStoreConfig('xpos/guest/guest_city') ?>',
            'statecounty': jQuery('#order-shipping_address_address_statecounty').val() != '' ? jQuery('#order-shipping_address_address_statecounty').val() : '<?php echo Mage::getStoreConfig('xpos/guest/guest_statecounty') ?>',
            'company': jQuery('#order-shipping_address_address_company').val() != '' ? jQuery('#order-shipping_address_address_company').val() : '<?php echo Mage::getStoreConfig('xpos/guest/guest_company') ?>',
            'outofcityarea': jQuery('#order-shipping_address_address_outofcityarea').val() != '' ? jQuery('#order-shipping_address_address_outofcityarea').val() : '<?php echo Mage::getStoreConfig('xpos/guest/guest_outofcityarea') ?>',
            'country_id': jQuery('#order-shipping_address_address_country_id').val() != '' ? jQuery('#order-shipping_address_address_country_id').val() : '<?php echo Mage::getStoreConfig('xpos/guest/country_id'); ?>',
            'region_id': jQuery('#order-shipping_address_address_region_id').val() != '' ? jQuery('#order-shipping_address_address_region_id').val() : '<?php echo Mage::getStoreConfig('xpos/guest/region_id'); ?>',
            'postcode': jQuery('#order-shipping_address_address_postcode').val() != '' ? jQuery('#order-shipping_address_address_postcode').val() : '<?php echo Mage::getStoreConfig('xpos/guest/guest_postal_code'); ?>',
            'telephone': jQuery('#order-shipping_address_address_telephone').val() != '' ? jQuery('#order-shipping_address_address_telephone').val() : '<?php echo Mage::getStoreConfig('xpos/guest/guest_phone') ?>'
        };
        setAdd(newAddress, true);
    }

    order.shippingAddressContainer = '<?php echo $_fieldsContainerId ?>';
    order.setAddresses(<?php echo $this->getAddressCollectionJson() ?>);

    function enableBilling(e) {
        if (e.checked) {
            jQuery('#billing-overlay').show();
            $('order-billing-address-content').hide();
        } else {
            $('order-billing-address-content').show();
            $('order-address-content').show();
            jQuery('input#order-shipping_same_as_billing').attr('checked', false);

            jQuery('#billing-overlay').hide();
            jQuery('#shipping-overlay').hide();

        }
        e.disabled = false;
    }

    function enableShipping(e) {
        if (e.checked) {
            jQuery('#shipping-overlay').show();
            $('order-address-content').hide();
        } else {
            $('order-billing-address-content').show();
            $('order-address-content').show();
            jQuery('input#order-billing_same_as_billing').attr('checked', false);

            jQuery('#shipping-overlay').hide();
            jQuery('#billing-overlay').hide();
        }
        e.disabled = false;
    }

    function clearShippingRegion() {
        jQuery('#order-shipping_address_address_region').val('');
        jQuery('#order-shipping_address_address_region_id').val('');

        setTimeout(function () {
            if (jQuery('#order-shipping_address_address_region_id').is(":disabled")) {
                jQuery('#uniform-order-shipping_address_address_region_id').hide('slow');
            } else {
                jQuery('#uniform-order-shipping_address_address_region_id').show('slow');
            }
        }, 10);

    }

    function clearBillingRegion() {
        jQuery('#order-billing_address_address_region').val('');
        jQuery('#order-billing_address_address_region_id').val('');

        setTimeout(function () {
            if (jQuery('#order-billing_address_address_region_id').is(":disabled")) {
                jQuery('#uniform-order-billing_address_address_region_id').hide('slow');
            } else {
                jQuery('#uniform-order-billing_address_address_region_id').show('slow');
            }
        }, 10);
    }

    function updateShippingRates() {
        return;
        if (window.isApplyingRp) {
            window.isApplyingRp = false;
            return;
        }
        jQuery('#order-shipping_address_address_region_virtual').hide();
        if (isOnline()) {
            var data = order.serializeData(order.shippingAddressContainer).toObject();
            order.isShippingMethodReseted = false;
            data.collect_shipping_rates = 1;
            data.reload_order = jQuery('#reload_order').val();
            if (!initialLoad) {
                if (window.isIntegrateRP != '0' || window.isIntegrateWebtexGiftCard != '0') {
                    order.loadArea(['shipping_method', 'totals', 'coupons'], true, data);
                } else {
                    order.loadArea(['shipping_method', 'totals'], true, data);
                }
            }
        }
    }

    shippingRegionUpdater = new RegionUpdater('order-shipping_address_address_country_id', 'order-shipping_address_address_region', 'order-shipping_address_address_region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'order-billing_address_address_postcode');
    billingRegionUpdater = new RegionUpdater('order-billing_address_address_country_id', 'order-billing_address_address_region', 'order-billing_address_address_region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'order-billing_address_address_postcode');

    jQuery('#clear_shipping_address').click(function () {
        jQuery('#order-shipping_address_address_firstname').val('');
        jQuery('#order-shipping_address_address_lastname').val('');
        jQuery('#order-shipping_address_address_street0').val('');
        jQuery('#order-shipping_address_address_city').val('');
        jQuery('#order-shipping_address_address_country_id').val('');
        jQuery('#order-shipping_address_address_region').val('');
        jQuery('#order-shipping_address_address_region').show();
        jQuery('#order-shipping_address_address_region_id').hide();
        jQuery('#order-shipping_address_address_postcode').val('');
        jQuery('#order-shipping_address_address_telephone').val('');
        jQuery('#order-shipping_address_address_region_id').attr('disabled', true);
        jQuery('#order-shipping_address_address_company').val('')
        jQuery.uniform.update();
        clearShippingRegion();
    });

    jQuery('#clear_billing_address').click(function () {
        jQuery('#order-billing_address_address_firstname').val('');
        jQuery('#order-billing_address_address_lastname').val('');
        jQuery('#order-billing_address_address_street0').val('');
        jQuery('#order-billing_address_address_city').val('');
        jQuery('#order-billing_address_address_country_id').val('');
        jQuery('#order-billing_address_address_region_id').val('');
        jQuery('#order-billing_address_address_region').val('');
        jQuery('#order-billing_address_address_region').show();
        jQuery('#order-billing_address_address_region_id').hide();
        jQuery('#order-billing_address_address_postcode').val('');
        jQuery('#order-billing_address_address_telephone').val('');
        jQuery('#order-billing_address_address_region_id').attr('disabled', true);
        jQuery.uniform.update();
        jQuery('#order-billing_address_address_company').val('')
        clearBillingRegion();

    });

    jQuery('#copy-from-billing-address').click(function () {
        jQuery('#order-shipping_address_address_firstname').val(jQuery('#order-billing_address_address_firstname').val());
        jQuery('#order-shipping_address_address_lastname').val(jQuery('#order-billing_address_address_lastname').val());
        jQuery('#order-shipping_address_address_street0').val(jQuery('#order-billing_address_address_street0').val());
        jQuery('#order-shipping_address_address_city').val(jQuery('#order-billing_address_address_city').val());
        jQuery('#order-shipping_address_address_country_id').val(jQuery('#order-billing_address_address_country_id').val());
        shippingRegionUpdater.update()
        jQuery('#order-shipping_address_address_region_id').val(jQuery('#order-billing_address_address_region_id').val());
        jQuery('#order-shipping_address_address_region').val(jQuery('#order-billing_address_address_region').val());
        jQuery('#order-shipping_address_address_postcode').val(jQuery('#order-billing_address_address_postcode').val());
        jQuery('#order-shipping_address_address_telephone').val(jQuery('#order-billing_address_address_telephone').val());
        jQuery('#order-shipping_address_address_company').val(jQuery('#order-billing_address_address_company').val());
        /***********Develop By Metizsoft***************/
        copybillingtoshipadd();
        jQuery('#order-shipping_address_address_outofcityarea').val(jQuery('#order-billing_address_address_outofcityarea').val());
        /***********Develop By Metizsoft***************/

        jQuery.uniform.update();
        setTimeout(function () {
            if (jQuery('#order-shipping_address_address_region_id').is(":disabled")) {
                jQuery('#uniform-order-shipping_address_address_region_id').hide('slow');
            } else {
                jQuery('#uniform-order-shipping_address_address_region_id').show('slow');
            }
        }, 10);
    });

    function copyShippingToBilling() {
        jQuery('#order-billing_address_address_firstname').val(jQuery('#order-shipping_address_address_firstname').val());
        jQuery('#order-billing_address_address_lastname').val(jQuery('#order-shipping_address_address_lastname').val());
        jQuery('#order-billing_address_address_street0').val(jQuery('#order-shipping_address_address_street0').val());
        jQuery('#order-billing_address_address_city').val(jQuery('#order-shipping_address_address_city').val());
        jQuery('#order-billing_address_address_country_id').val(jQuery('#order-shipping_address_address_country_id').val());
        billingRegionUpdater.update()
        jQuery('#order-billing_address_address_region_id').val(jQuery('#order-shipping_address_address_region_id').val());
        jQuery('#order-billing_address_address_region').val(jQuery('#order-shipping_address_address_region').val());
        jQuery('#order-billing_address_address_postcode').val(jQuery('#order-shipping_address_address_postcode').val());
        jQuery('#order-billing_address_address_telephone').val(jQuery('#order-shipping_address_address_telephone').val());
        jQuery('#order-billing_address_address_company').val(jQuery('#order-shipping_address_address_company').val());
        /***********Develop By Metizsoft***************/
        $selectcounty = jQuery('#order-shipping_address_address_statecounty').val();

        jQuery('#order-billing_address_address_statecounty').html(jQuery('#order-shipping_address_address_statecounty').html());
        jQuery('#order-billing_address_address_statecounty option[value="' + $selectcounty + '"]').prop('selected', true);

        $selectedcity = jQuery('#order-shipping_address_address_city').val();

        jQuery('#order-billing_address_address_city').html(jQuery('#order-shipping_address_address_city').html());
        jQuery('#order-billing_address_address_city option[value="' + $selectedcity + '"]').prop('selected', true);
        jQuery('#order-billing_address_address_outofcityarea').val(jQuery('#order-shipping_address_address_outofcityarea').val());
        /***********Develop By Metizsoft***************/
        jQuery.uniform.update();
        setTimeout(function () {
            if (jQuery('#order-shipping_address_address_region_id').is(":disabled")) {
                jQuery('#uniform-order-shipping_address_address_region_id').hide('slow');
            } else {
                jQuery('#uniform-order-shipping_address_address_region_id').show('slow');
            }
        }, 10);
    }
    jQuery(document).ready(function () {
        <?php if(isset($order['customer_id'])){ ?>
        <?php
        if(Mage::getModel('xpos/integrate')->isIntegrateRp()){
         Mage::getModel('xpos/integrate')->setSessionCustomer($order['customer_id']);
         ?>
        <?php
        $rewardPoints = Mage::getModel('xpos/integrate')->getBalanceAccountFormated($order['customer_id']);
        $_pointMoney = Mage::getModel('xpos/integrate')->getPointMoneyByCustomerIdDefault($order['customer_id']);
        if($_pointMoney){
        $_pointMoney = ' (' . $_pointMoney . ')';
        }
        ?>
        setRp();
        <?php }?>
        jQuery('#order_customer_id').val(<?php echo $customer['entity_id'] ?>);
        jQuery('#order_account_email').val('<?php echo $customer['email'] ?>');
        jQuery("#customer_options").removeClass('search-customer');
        jQuery("#customer_options").addClass('delete-customer');
        jQuery("#customer_options").attr('onclick', 'come_back_guest()');
        jQuery('#emailreceipt').val('<?php echo $customer['email'] ?>');
        jQuery("#customer_name").html('<?php echo $customer['firstname'] . " " . $customer['lastname']; ?>');
        <?php }else{ ?>
        getCustomerDefault(document.getElementById('change_customer_guest'));
        <?php
        if(Mage::getModel('xpos/integrate')->isIntegrateRp()){
        Mage::getModel('xpos/integrate')->setSessionCustomer(Mage::helper('xpos/configXPOS')->getDefaultCustomerId()) ?>
        <?php
        $rewardPoints = Mage::getModel('xpos/integrate')->getBalanceAccountFormated(Mage::helper('xpos/configXPOS')->getDefaultCustomerId());
        $_pointMoney = Mage::getModel('xpos/integrate')->getPointMoneyByCustomerIdDefault(Mage::helper('xpos/configXPOS')->getDefaultCustomerId());
        if($_pointMoney){
        $_pointMoney = ' (' . $_pointMoney . ')';
        }
        ?>
        setRp();
        <?php }?>
        <?php } ?>

        /***********Develop By Metizsoft***************/
        var $billing_statecounty_name = jQuery('#order-billing_address_address_statecounty').attr('name');
        var $billing_statecounty_id = jQuery('#order-billing_address_address_statecounty').attr('id');
        var $billing_statecounty_val = jQuery('#order-billing_address_address_statecounty').val();
        var $select_statecounty = '<select onchange="getcitybill(this)" id="' + $billing_statecounty_id + '" name="' + $billing_statecounty_name + '" class="validate-select"><option value="' + $billing_statecounty_val + '">' + $billing_statecounty_val + '</option></select>';
        jQuery('#order-billing_address_address_statecounty').replaceWith($select_statecounty);

        var $billing_city_name = jQuery('#order-billing_address_address_city').attr('name');
        var $billing_city_id = jQuery('#order-billing_address_address_city').attr('id');
        var $billing_city_val = jQuery('#order-billing_address_address_city').val();
        var $select_city = '<select id="' + $billing_city_id + '" name="' + $billing_city_name + '" class="validate-select"><option value="' + $billing_city_val + '">' + $billing_city_val + '</option></select>';
        jQuery('#order-billing_address_address_city').replaceWith($select_city);

        var $shipping_statecounty_name = jQuery('#order-shipping_address_address_statecounty').attr('name');
        var $shipping_statecounty_id = jQuery('#order-shipping_address_address_statecounty').attr('id');
        var $shipping_statecounty_val = jQuery('#order-shipping_address_address_statecounty').val();
        var $select_statecounty = '<select onchange="getcityship(this)" id="' + $shipping_statecounty_id + '" name="' + $shipping_statecounty_name + '" class="validate-select"><option value="' + $shipping_statecounty_val + '">' + $shipping_statecounty_val + '</option></select>';
        jQuery('#order-shipping_address_address_statecounty').replaceWith($select_statecounty);

        var $shipping_city_name = jQuery('#order-shipping_address_address_city').attr('name');
        var $shipping_city_id = jQuery('#order-shipping_address_address_city').attr('id');
        var $shipping_city_val = jQuery('#order-shipping_address_address_city').val();
        var $select_city = '<select id="' + $shipping_city_id + '" name="' + $shipping_city_name + '" class="validate-select"><option value="' + $shipping_city_val + '">' + $shipping_city_val + '</option></select>';
        jQuery('#order-shipping_address_address_city').replaceWith($select_city);

//        jQuery('#order-billing_address_address_region_id').attr('onchange', 'getcountybill(this)');
//        jQuery('#order-shipping_address_address_region_id').attr('onchange', 'getcountyship(this)');

        var $billing_ooca_name = jQuery('#order-billing_address_address_outofcityarea').attr('name');
        var $billing_ooca_id = jQuery('#order-billing_address_address_outofcityarea').attr('id');
        var $billing_ooca_val = jQuery('#order-billing_address_address_outofcityarea').val();
        if ($billing_ooca_val == 9) {
            var $selectedno = 'selected=selected';
        } else {
            var $selectedyes = 'selected=selected';
        }
        var $select_ooca = '<select id="' + $billing_ooca_id + '" name="' + $billing_ooca_name + '" class="validate-select">'
            + '<option value="9" ' + $selectedno + '>No</option>'
            + '<option value="10" ' + $selectedyes + '>Yes</option>'
            + '</select>';
        jQuery('#order-billing_address_address_outofcityarea').replaceWith($select_ooca);

        var $ship_ooca_name = jQuery('#order-shipping_address_address_outofcityarea').attr('name');
        var $ship_ooca_id = jQuery('#order-shipping_address_address_outofcityarea').attr('id');
        var $ship_ooca_val = jQuery('#order-shipping_address_address_outofcityarea').val();
        if ($ship_ooca_val == 9) {
            var $selectedno = 'selected=selected';
        } else {
            var $selectedyes = 'selected=selected';
        }
        var $select_ooca = '<select id="' + $ship_ooca_id + '" name="' + $ship_ooca_name + '" class="validate-select">'
            + '<option value="9" ' + $selectedno + '>No</option>'
            + '<option value="10" ' + $selectedyes + '>Yes</option>'
            + '</select>';
        jQuery('#order-shipping_address_address_outofcityarea').replaceWith($select_ooca);

        /***********Develop By Metizsoft***************/

    });
    <?php if(Mage::getModel('xpos/integrate')->isIntegrateRp()){ ?>
    function setRp() {
        var currentCustomer = '<h4 style="font-size: 14px">' + jQuery('#customer_name').html() + '</h4>';
        var points =
            '<h5 style="font-size: 8px;text-transform: capitalize;color: #1b376c"> Balance is: ' +
            '<?php echo $rewardPoints ?>' + '<?php echo $_pointMoney ?>' +
            '</h5>';
        var text = currentCustomer + points;
        jQuery('#customer_name').html(text);
    }
    <?php }?>

    /***********Develop By Metizsoft***************/

    function getcountybill(selectElement) {
        var reloadurl = '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/taxgenerate_statetax/countyadminadd') ?>';
        new Ajax.Request(reloadurl, {
            method: 'get',
            parameters: {stateid: selectElement.value},
            onComplete: function (stateform) {
                $('order-billing_address_address_statecounty').update(stateform.responseText);
                $('order-billing_address_address_city').update('<option value="">Please Select</option>');
                jQuery("#order-billing_address_address_statecounty,#order-billing_address_address_city").uniform();
            }
        });
    }
    function getcitybill(selectElement) {
        console.log('dfsdfsd')
        var reloadurl = '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/taxgenerate_statetax/cityadminadd') ?>';
        new Ajax.Request(reloadurl, {
            method: 'get',
            parameters: {county: selectElement.value},
            onComplete: function (stateform) {
                $('order-billing_address_address_city').update(stateform.responseText);
                jQuery("#order-billing_address_address_city").uniform();
            }
        });
    }
    function getcountyship(selectElement) {
        var reloadurl = '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/taxgenerate_statetax/countyadminadd') ?>';
        new Ajax.Request(reloadurl, {
            method: 'get',
            parameters: {stateid: selectElement.value},
            onComplete: function (stateform) {
                $('order-shipping_address_address_statecounty').update(stateform.responseText);
                $('order-shipping_address_address_city').update('<option value="">Please Select</option>');
                jQuery("#order-shipping_address_address_statecounty,#order-shipping_address_address_city").uniform();
            }
        });
    }
    function getcityship(selectElement) {
        var reloadurl = '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/taxgenerate_statetax/cityadminadd') ?>';
        new Ajax.Request(reloadurl, {
            method: 'get',
            parameters: {county: selectElement.value},
            onComplete: function (stateform) {
                $('order-shipping_address_address_city').update(stateform.responseText);
                jQuery("#order-shipping_address_address_city").uniform();
            }
        });
    }
    /*************** Get default value on county and city dopdown ******************/
    setTimeout(getcounty, 1000);
    setTimeout(getcity, 1000);

    function getcounty() {
        var $statebill = jQuery('#order-billing_address_address_region_id').val();
        var $stateship = jQuery('#order-shipping_address_address_region_id').val();
        var $countybill = jQuery('#order-billing_address_address_statecounty').val();
        //alert($countybill);
        var $countyship = jQuery('#order-shipping_address_address_statecounty').val();
        var reloadurl = '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/taxgenerate_statetax/countyadminadd') ?>';
        /*new Ajax.Request(reloadurl, {
         method: 'get',
         parameters: {stateid: $statebill},
         onComplete: function(stateform) {
         $('order-billing_address_address_statecounty').update(stateform.responseText);
         jQuery('#order-billing_address_address_statecounty option[value="'+$countybill+'"]').prop('selected', true);
         }
         });
         new Ajax.Request(reloadurl, {
         method: 'get',
         parameters: {stateid: $stateship},
         onComplete: function(stateform) {
         $('order-shipping_address_address_statecounty').update(stateform.responseText);
         jQuery('#order-shipping_address_address_statecounty option[value="'+$countyship+'"]').prop('selected', true);
         }
         });*/

        jQuery.ajax({
            url: reloadurl,
            type: 'get',
            data: {stateid: $statebill},
            success: function (stateform) {
                jQuery('#order-billing_address_address_statecounty').html(stateform);
                jQuery('#order-billing_address_address_statecounty option[value="' + $countybill + '"]').prop('selected', true);
            }
        });

        jQuery.ajax({
            url: reloadurl,
            type: 'get',
            data: {stateid: $stateship},
            success: function (stateform) {
                jQuery('#order-shipping_address_address_statecounty').html(stateform);
                jQuery('#order-shipping_address_address_statecounty option[value="' + $countyship + '"]').prop('selected', true);
            }
        });
    }
    function getcity() {
        jQuery("select").uniform();
        var $countybill = jQuery('#order-billing_address_address_statecounty').val();
        var $citybill = jQuery('#order-billing_address_address_city').val();
        var $countyship = jQuery('#order-shipping_address_address_statecounty').val();
        var $cityship = jQuery('#order-shipping_address_address_city').val();


        var reloadurl = '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/taxgenerate_statetax/cityadminadd') ?>';

        jQuery.ajax({
            url: reloadurl,
            type: 'get',
            data: {county: $countybill},
            success: function (stateform) {
                jQuery('#order-billing_address_address_city').html(stateform);
                jQuery('#order-billing_address_address_city option[value="' + $citybill + '"]').prop('selected', true);
            }
        });
        jQuery.ajax({
            url: reloadurl,
            type: 'get',
            data: {county: $countyship},
            success: function (stateform) {
                jQuery('#order-shipping_address_address_city').html(stateform);
                jQuery('#order-shipping_address_address_city option[value="' + $cityship + '"]').prop('selected', true);
                jQuery("select").uniform();
            }
        });
        /*new Ajax.Request(reloadurl, {
         method: 'get',
         parameters: {county: $countybill},
         onComplete: function(stateform) {
         $('order-billing_address_address_city').update(stateform.responseText);
         jQuery('#order-billing_address_address_city option[value="'+$citybill+'"]').prop('selected', true);
         }
         });
         new Ajax.Request(reloadurl, {
         method: 'get',
         parameters: {county: $countybill},
         onComplete: function(stateform) {
         $('order-shipping_address_address_city').update(stateform.responseText);
         jQuery('#order-shipping_address_address_city option[value="'+$cityship+'"]').prop('selected', true);
         jQuery("select").uniform();
         }
         });*/

        /*
         */

    }
    //
    function switchBillingAddress(obj) {
        var address = obj.value;
        var optionTagID = '#customer_billing_address_list option[value=' + address + ']'
        optionTag = jQuery(optionTagID);
        jQuery('#order-billing_address_address_firstname').val(optionTag.attr('firstname'));
        jQuery('#order-billing_address_address_lastname').val(optionTag.attr('lastname'));
        jQuery('#order-billing_address_address_street0').val(optionTag.attr('street'));
        jQuery('#order-billing_address_address_country_id').val(optionTag.attr('country_id'));
        billingRegionUpdater.update();
        var city = optionTag.attr('city');
        jQuery('#order-billing_address_address_region').val(optionTag.attr('region'));
        jQuery('#order-billing_address_address_region_id').val(optionTag.attr('region_id'));
        jQuery('#order-billing_address_address_postcode').val(optionTag.attr('postcode'));
        jQuery('#order-billing_address_address_telephone').val(optionTag.attr('telephone'));
        jQuery('#order-billing_address_address_statecounty').val(optionTag.attr('statecounty'));
        jQuery('#order-billing_address_address_company').val(optionTag.attr('company'));
        jQuery('#order-billing_address_address_outofcityarea').val(optionTag.attr('outofcityarea'));
        if (city) {
            var select_billing_city = '' +
                '<option selected value="' + city
                + '">' + city + '</option>';
            jQuery('#order-billing_address_address_city').empty();
            jQuery('#order-billing_address_address_city').append(select_billing_city);
            jQuery('#order-billing_address_address_city').val(city);
        } else {
            var select_billing_city = '<option value="">Please Select City</option>';
            jQuery('#order-billing_address_address_city').empty();
            jQuery('#order-billing_address_address_city').append(select_billing_city);
        }
//        jQuery('#order-billing_address_address_company').val(optionTag.attr('company'));


        setTimeout(function () {
            jQuery.uniform.update()
            if (jQuery('#order-billing_address_address_region_id').is(":disabled")) {
                jQuery('#uniform-order-billing_address_address_region_id').hide('slow');
            } else {
                jQuery('#uniform-order-billing_address_address_region_id').show('slow');
            }
        }, 10);
    }
    function switchShippingAddress(obj) {
        var address = obj.value;
        var optionTagID = '#customer_shipping_address_list option[value=' + address + ']';
        optionTag = jQuery(optionTagID);

        if(optionTag.attr('address_id')){
            jQuery('#order-shipping_address_address_id').val(optionTag.attr('address_id'));
        }
        jQuery('#order-shipping_address_address_firstname').val(optionTag.attr('firstname'));
        jQuery('#order-shipping_address_address_lastname').val(optionTag.attr('lastname'));
        jQuery('#order-shipping_address_address_salestaxid').val(optionTag.attr('salestaxid'));
        jQuery('#order-shipping_address_address_entityname').val(optionTag.attr('entityname'));
        jQuery('#order-shipping_address_address_street0').val(optionTag.attr('street'));
        jQuery('#order-shipping_address_address_country_id').val(optionTag.attr('country_id'));
        shippingRegionUpdater.update();
        var city = optionTag.attr('city');
        jQuery('#order-shipping_address_address_city').val(optionTag.attr('city'));
        jQuery('#order-shipping_address_address_region').val(optionTag.attr('region'));
        jQuery('#order-shipping_address_address_region_id').val(optionTag.attr('region_id'));
        jQuery('#order-shipping_address_address_postcode').val(optionTag.attr('postcode'));
        jQuery('#order-shipping_address_address_telephone').val(optionTag.attr('telephone'));
        jQuery('#order-shipping_address_address_statecounty').val(optionTag.attr('statecounty'));
        jQuery('#order-shipping_address_address_company').val(optionTag.attr('company'));
        jQuery('#order-shipping_address_address_outofcityarea').val(optionTag.attr('outofcityarea'));
        var select_shipping_city = '' +
            '<option selected value="' + city
            + '">' + city + '</option>';
        jQuery('#order-shipping_address_address_city').empty();
        jQuery('#order-shipping_address_address_city').append(select_shipping_city);
        jQuery('#order-shipping_address_address_city').val(city);

//        jQuery('#order-shipping_address_address_company').val(optionTag.attr('company'));

        setTimeout(function () {
            jQuery.uniform.update()
            if (jQuery('#order-shipping_address_address_region_id').is(":disabled")) {
                jQuery('#uniform-order-shipping_address_address_region_id').hide('slow');
            } else {
                jQuery('#uniform-order-shipping_address_address_region_id').show('slow');
            }
        }, 10);

        jQuery("#entity_name").html(optionTag.attr('entityname'));
        jQuery("#company_name").html(optionTag.attr('company'));
        jQuery("#sale_tax_id").html(optionTag.attr('salestaxid'));
        jQuery("#county_name").html(optionTag.attr('statecounty'));
        jQuery("#city_limit").html(optionTag.attr('outofcityarea') == 10 ? 'Yes' : 'No' );

        jQuery("#entity_name").attr('title',optionTag.attr('entityname'));
        jQuery("#company_name").attr('title',optionTag.attr('company'));
        jQuery("#sale_tax_id").attr('title',optionTag.attr('salestaxid'));
        jQuery("#county_name").attr('title',optionTag.attr('statecounty'));
        jQuery("#city_limit").attr('title',optionTag.attr('outofcityarea') == 10 ? 'Yes' : 'No' );

        jQuery("#customer_selected_street").html(optionTag.attr('street') ? optionTag.attr('street') + ',' : '');
        jQuery("#customer_selected_city").html(optionTag.attr('city') ? optionTag.attr('city') + ',' : '');
        jQuery("#customer_selected_state").html(optionTag.attr('region') ? optionTag.attr('region') + ',' : '');
        jQuery("#customer_selected_zipcode").html(optionTag.attr('postcode')? optionTag.attr('postcode') : '');
    }
    function copybillingtoshipadd() {
        $county = jQuery('#order-billing_address_address_statecounty').html();
        $selectcounty = jQuery('#order-billing_address_address_statecounty').val();

        jQuery('#order-shipping_address_address_statecounty').html($county);
        jQuery('#order-shipping_address_address_statecounty option[value="' + $selectcounty + '"]').prop('selected', true);

        $city = jQuery('#order-billing_address_address_city').html();
        $selectedcity = jQuery('#order-billing_address_address_city').val();

        jQuery('#order-shipping_address_address_city').html($city);
        jQuery('#order-shipping_address_address_city option[value="' + $selectedcity + '"]').prop('selected', true);

    }
    /***********Develop By Metizsoft***************/
</script>
