<?php
/**
 * Created by PhpStorm.
 * User: Le Nam
 * Date: 7/18/14
 * Time: 5:01 PM
 */
//$data = $this->getRequest()->getPost('creditmemo');
$data_product = Mage::getSingleton('adminhtml/session')->getData('credit_data');
$adjustment_fee = $data_product['adjustment_negative'];
$lstitems = $data_product['items'];
$lstId = array();
foreach($lstitems as $itemId=>$itemQty){
    if($itemQty>0){
        $order_id = Mage::getModel('sales/order_item')->load($itemId)->getData('order_id');
        $lstId[$itemId] = $itemQty ;
    }
}

$logo_receipt = "";
if(is_file('media/xpos/' . Mage::getStoreConfig('xpos/customize/logo_receipt'))){
    $logo_receipt = Mage::getBaseUrl('media') . 'xpos/' . Mage::getStoreConfig('xpos/customize/logo_receipt');
}

$data = $this->getSource();

//$total_paid = $info_order['totalPaid'];
//$customer_name = Mage::getStoreConfig('xpos/guest/guest_name');
//if ($customer != 'guest') {
//    $customer_name = $customer;
//}

$cashier_name = $this->getRequest()->getParam('cashier_name');

?>

<div id="store_information">
    <div style="width: 128px;">
    <?php
    if ($logo_receipt != ''){
        echo "<img style='width: 100%' src='$logo_receipt' /><br/>";
    }
    ?>
    </div>
    <?php
    if (Mage::getStoreConfig('general/store_information/name', Mage::helper('xpos/product')->getCurrentSessionStoreId()) != '') {
        echo Mage::getStoreConfig('general/store_information/name', Mage::helper('xpos/product')->getCurrentSessionStoreId()) . "<br/>";
    }
    ?>
    <?php
    if (Mage::getStoreConfig('general/store_information/address', Mage::helper('xpos/product')->getCurrentSessionStoreId()) != '') {
        $address = Mage::getStoreConfig('general/store_information/address');
        $storeid = Mage::helper('xpos/product')->getCurrentSessionStoreId();
        echo str_replace("\n", "<br/>",$address , $storeid) . "<br/>";
    }
    ?>

    <?php if ($store_phone = Mage::getStoreConfig('general/store_information/phone', Mage::helper('xpos/product')->getCurrentSessionStoreId())): ?>
        T: <?php echo $store_phone ?>
    <?php endif; ?>
</div>
<h1 class="a-center"><?php echo $this->__("Refund"); ?></h1>


<div class="entry-edit">
    <table cellspacing="0" class="box-left form-list">
        <tr>
            <td class="label"><label><?php echo Mage::helper('sales')->__("Order No."); ?></label></td>
            <td class="value"><strong><?php echo $data->getData('increment_id'); ?></strong></td>
        </tr>
        <tr>
            <td class="label"><label><?php echo Mage::helper('sales')->__('Date') ?></label></td>
            <td class="value"><strong><?php echo date('d/m/Y', strtotime($data->getCreatedAt())) ?></strong></td>
        </tr>
        <tr>
            <td class="label"><label><?php echo Mage::helper('sales')->__('Customer') ?></label></td>
            <td class="value"><strong><?php echo $data->getData('customer_firstname').$data->getData('customer_lastname') ?></strong></td>
        </tr>
        <?php if(Mage::helper('xpos/configXPOS')->getEnableCashier()){?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Cashier') ?></label></td>
                <td class="value"><strong id="cashier_name"><?php echo $cashier_name ?></strong></td>
            </tr>
        <?php } ?>

        <tr>
            <td class="label"><label><?php echo Mage::helper('sales')->__("Time"); ?></label></td>
            <td class="value"><strong><?php echo date('H:i:s A', time()) ?></strong></td>
        </tr>
    </table>
    <div class="clear"></div>
</div>
<div class="clear"></div>


<?php $_items = $this->getCreditmemo()->getAllItems() ?>

<div class="grid np">
    <div class="hor-scroll">
        <table cellspacing="0" class="data order-tables">
            <col/>
            <col width="1"/>
            <col width="1"/>
            <col width="1"/>
            <thead>
            <tr class="headings">
                <th class="no_col"><b><?php echo $this->helper('sales')->__('No') ?></b></th>
                <th><b><?php echo $this->helper('sales')->__('Description') ?></b></th>
                <th class="a-center refund-qty"><b><?php echo $this->helper('sales')->__('Qty') ?></b></th>
                <th class="refund-price"><b><?php echo $this->helper('sales')->__('Price') ?></b></th>
                <th class="refund-total last"><b><?php echo $this->helper('sales')->__('Row Total') ?></b></th>
            </tr>
            </thead>
            <tbody>
            <?php $i = 0;

            foreach ($_items as $item){
                //if( $item['parent_item_id'] == null){
                if($item->getPrice() > 0){
                    ?>
                    <?php $i++; ?>
                    <tr class="border <?php echo $i % 2 ? 'even' : 'odd' ?>">
                        <td class="no_col"><?php echo $i ?></td>

                        <td>
                            <div id="order_item_<?php echo $item['item_id']; ?>" class="item-container">
                                <div class="item-text">
                                    <h5 class="title"><span
                                            id="order_item_<?php echo $item['item_id']; ?>_title"><?php echo $item['name']; ?></span>
                                    </h5>

                                    <div><strong>SKU:</strong> <?php echo $item['sku']; ?></div>
                                </div>
                            </div>
                        </td>
                        <td class="a-center refund-qty"><?php echo ($item->getQty() * 1) ?></td>
                        <td class="a-right refund-price">
                            <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
                                <span class="price-excl-tax">
                                    <?php echo Mage::helper('core')->formatPrice($item->getPrice()) ?>
                                </span>
                            <?php endif; ?>
                            <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
                                <span class="price-incl-tax">
                                    <?php echo Mage::helper('core')->formatPrice($item->getPriceInclTax()) ?>
                                </span>
                            <?php endif; ?>
                        </td>

                        <td class="a-right refund-total last">
                            <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
                                <span class="price-excl-tax">
                                <span
                                    class="price"><?php echo Mage::helper('core')->formatPrice($item['qty']*$item->getPrice()); ?></span>
                            </span>
                                <br/>
                            <?php endif; ?>
                            <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
                                <span class="price-incl-tax">
                                <span
                                    class="price"><?php echo Mage::helper('core')->formatPrice($item['qty']*$item->getPriceInclTax()); ?></span>
                            </span>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<br/>

<div class="clear"></div>
<div class="entry-edit">

    <table cellspacing="0" width="100%">

        <tbody>
        <?php
            $_totals = $this->getTotals('footer')
        ?>
        <?php if ($_totals):?>
        <?php foreach ($this->getTotals('footer') as $_code => $_total): ?>
            <?php if ($_total->getBlockName()): ?>
                <?php /*echo $this->getChildHtml($_total->getBlockName(), false);*/ ?>
            <?php else:?>
                <tr>
                    <td class="label">
                        <strong><?php  echo $this->escapeHtml($_total->getLabel()); ?></strong>
                    </td>
                    <td class="emph a-right">
                        <strong><span class="price">
                            <?php echo $this->formatValue($_total) ?>
                        </span></strong>
                    </td>
                </tr>

            <?php endif?>
        <?php endforeach?>
        </tfoot>
        <?php endif?>
        </tbody>
    </table>

</div>
<div class="clear"></div>

<script type="text/javascript">
    document.observe("dom:loaded", function () {
        window.print();
        window.onfocus = function () {
            window.close();
        }
    });
</script>
<?php echo $this->getChildHtml('popup_window'); ?>
<script type="text/javascript">
    //<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0, 30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
    //]]>
</script>
