<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <meta charset="utf-8" />

    <!--INTERNAL STYLE SHEET-->
    <style>
        body{
            width: 384px;
        }
        @media (max-width: 384px) {
            .items-view table .row-total {
                display: none;
            }items-view table td[data-metadata='qty']
            .methods {
                display: block !important;
            }
        }
        @media (max-width: 380px) {
            .items-view table .item-name {
                max-width: 120px;
            }
            .items-view table .price-container,
            .items-view table .tax {
                display: none !important;
            }
            .items-view table .row-total {
                display: table-cell !important;
            }
        }

        * {
            box-sizing: border-box;
        }
        html {
            font-family: <?php echo $this->getFont(); ?>;
            font-size: 13px;
        }
        body, h1, h2, h3, h4, h5, h6, ul {
            padding: 0;
            margin: 0;
            font-weight: normal;
        }
        table {
            border-spacing: 0;
        }
        ul {
            list-style: none;
        }
        .flex-container {
            display: -webkit-flex;
            display: flex;
            -webkit-justify-content: space-around;
            justify-content: space-around;
        }

        .paper {
            margin: 0;
            padding: 15px 0;
        }

        .logo-container, .store-info {
            text-align: center;
        }
        .store-info {
            /*margin-bottom: 7px;*/
        }
        .store-info .name {
            font-weight: 800;
            text-align: inherit;
        }

        #logo {
            font-family: Segoe UI, Arial, sans-serif;
            font-weight: 800;
            font-size: 32px;
        }

        #logo img {
            max-width: 200px;
        }

        .receipt-info {
            display: -webkit-flex;
            display: flex;
            -webkit-justify-content: space-between;
            justify-content: space-between;
            margin-bottom: 7px;
        }

        .receipt-info .customer-info {
            text-transform: uppercase;
        }

        .items-view {
            padding: 3px 0;
            margin-bottom: 7px;
        }
        .items-view table {
            width: 100%;
            text-align: right;
            font-size: inherit;
            font-weight: inherit;
            border-collapse: separate;
        }

        .items-view table thead {
            vertical-align: top;
        }

        .items-view table tbody {
            vertical-align: top;
        }

        .items-view table tbody tr td {
            padding: 5px 0;
        }

        .items-view table td,
        .items-view table th {
            border-left: 10px solid transparent;
        }

        .items-view table td:first-child,
        .items-view table th:first-child {
            border-left: none;
        }

        .items-view table .item-name {
            overflow: hidden;
            white-space: normal;
            text-transform: capitalize;
        }

        .items-view table .item-name .sku {
            display: block;
            text-transform: none;
        }

        .total-zone {
            margin-bottom: 7px;
            text-transform: uppercase;
        }
        .total-zone .title {
            display: -webkit-flex;
            display: flex;
            font-weight: 800;
            -webkit-justify-content: space-between;
            justify-content: space-between;
            -webkit-align-items: center;
            align-items: center;
        }

        .total-zone:before, .total-zone:after{
            content: '\0020';
            display: block;
            overflow: hidden;
            visibility: hidden;
            width: 0;
            height: 0
        }
        .total-zone:after {
            clear: both
        }

        .total-zone .title .literal {

        }
        .total-zone table {
            font-weight: inherit;
            font-size: inherit;
            width: 50%;
            float: left;
        }
        .methods {
            display: block;
            margin-bottom: 7px;
            text-transform: uppercase;
        }
        .footer {
            text-align: center;
        }
        .footer .highlight {
            text-transform: uppercase;
            font-weight: 400;
            font-size: 28px;
        }
        .footer .separate {

        }
        .date {
            text-align: right;
        }

        @media screen {
            .paper {
                margin: 15px auto;
                max-width: 600px;
            }
        }
        @media print {
            body {
                color: #000;
                background-color: #fff;
            }
        }
    </style>
</head>
<body>
    <div class="paper fluid-container">
        <div class="logo-container container">
            <?php echo $this->getChildHtml('logo'); ?>
        </div>
        <div class="store-info-container container">
            <?php $this->getChild('store_info')->setData("order", $this->getOrder()); ?>
            <?php echo $this->getChildHtml('store_info', false); ?>
        </div>
        <div class="receipt-info-container container">
            <?php $this->getChild('order_info')->setData("order", $this->getOrder()); ?>
            <?php echo $this->getChildHtml('order_info', false); ?>
        </div>
        <div class="methods-container container">
<!--            --><?php //$this->getChild('methods')->setData("order", $this->getOrder()); ?>
<!--            --><?php //echo $this->getChildHtml('methods', false); ?>
        </div>
        <div class="items-view-container container">
            <?php $this->getChild('items_view')->setData("order", $this->getOrder()); ?>
            <?php echo $this->getChildHtml('items_view', false); ?>
        </div>
        <div class="total-zone-container container">
            <?php $this->getChild('totals_zone')->setData("order", $this->getOrder()); ?>
            <?php echo $this->getChildHtml('totals_zone', false); ?>
        </div>
        <div class="fore-container container">
            <?php $this->getChild('fore')->setData("order", $this->getOrder()); ?>
            <?php echo $this->getChildHtml('fore', false); ?>
        </div>
    </div>

    <script type="text/javascript">
        /*
         * http://stackoverflow.com/questions/3196572/addloadevent-is-not-helping-with-onload-conflict#3196789
         */
        function addLoadEvent(func) {
            if (window.addEventListener)
                window.addEventListener('load', func, false);
            else if (window.attachEvent())
                window.attachEvent('onload', func);
            else {
                var old = window.onload;
                window.onload = function () {
                    if (old) old();
                    func();
                }
            }
        }

        addLoadEvent(function() {
            window.print();
            /*
             * @risk: Quick and Dirty
             * Auto close after printing
             */
            setTimeout(function() {window.close()}, 100);
        });
    </script>
</body>
</html>
