<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Categories</h4>
    </div>
    <div class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>

                <tr>
                    <td class="label"><label for="price">Categories <span class="required">*</span></label></td>
                    <td class="value">
                        <?php $_helper = Mage::helper('catalog/category') ?>
                        <?php $_category = Mage::getModel('catalog/category')->load($this->getCategoryId()) ?>
                        <?php $_subcategories = $_category->getChildrenCategories() ?>
                        <select name="category_ids" id="product_categories" multiple="true">
                            <?php if (count($_subcategories) > 0): ?>
                                <?php foreach($_subcategories as $_subcategory): ?>
                                    <option value="<?php echo $_subcategory->getId() ?>"><?php echo $_subcategory->getName() ?></option>
                                <?php endforeach ?>
                            <?php endif ?>
                        </select>
                    <td class="scope-label"><span class="nobr"></span></td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>
