<?php
//
//?>
<!--<ul id="payment_form_--><?php //echo $this->getMethodCode() ?><!--">-->
<!--    --><?php //$_code = $this->getMethodCode() ?>
<!--    <li>-->
<!--        <div class="input-box">-->
<!--            <div class="input-box">-->
<!--                <input type="checkbox" id="--><?php //echo $_code . '_checkbox' ?><!--" name="payment[sm_store_credit_pay_previous]" class="input-checkbox" value="--><?php //echo $this->getInfoData('sm_store_credit_pay_previous')?><!--"/>-->
<!--                <label for="--><?php //echo $_code . '_value' ?><!--">--><?php //echo Mage::helper('payment')->__('Pay Previous Balance') ?><!-- </label><br/>-->
<!--                <input type="text" id="--><?php //echo $_code . '_value' ?><!--" name="payment[sm_store_credit_pay_previous_value]" title="--><?php //echo Mage::helper('payment')->__('Pay Previous Balance') ?><!--" class="input-text validate-greater-than-zero" value="--><?php //echo $this->getInfoData('sm_store_credit_pay_previous_value')?><!--"/>-->
<!--            </div>-->
<!--        </div>-->
<!--    </li>-->
<!--</ul>-->
