<div class="block-content bestseller">
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
if ($_productCollection->count()):
$_iterator = 0;
 $i=1;
foreach($_productCollection as $_product): ?>

<div class="col-xs-12 col-sm-12 bestitem">
    <div class="col-xs-6 col-sm-12 col-lg-6">
    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(100); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
    </a>
    </div><div class="col-xs-6 col-sm-12 col-lg-6">
    <p><?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'),0,30) ?></p>
    <p><span><?php echo $this->getPriceHtml($_product, true) ?></span></p>
    <p>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true); ?>">
            More Info
        </a>
    </p>
    </div>
</div>
<?php
if($i == 5){
 break;   
}
$i++;
endforeach; // end products loop ?>
<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
<?php endif; // if product collection ?>
</div>
<div class="clear"></div>