<?php
$_productCollection = Mage::getModel('catalog/product')->getCollection();
$_productCollection->addAttributeToSelect('*')
                   ->addFieldToFilter('visibility', array(
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                   )) 
                   ->addFinalPrice()
                   ->getSelect()
                   ->where('price_index.final_price < price_index.price');
 
Mage::getModel('review/review')->appendSummary($_productCollection);
 
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    
<?php else: ?>
    <div class="page-title category-title">
            <h1>Our Special Products</h1>
    </div>
    <div class="category-products">
            <?php $_iterator = 0; ?>
        <table cellpadding="0" cellspacing="0" border="0">
            <tr>
                <?php foreach ($_productCollection as $_product): ?>
                    <td class="item col-xs-12 col-sm-4">
                        <div class="grid_wrap">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(228) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                        <div class="product-shop">
                                <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                                    <div class="desc_grid"><?php $small_getDescription = strip_tags($_product->getShortDescription());
                                 if (strlen($small_getDescription) < 70) echo($small_getDescription);
                                 else { echo mb_substr($small_getDescription, 0, 70,'UTF-8').'...';} ?></div>
                                    <?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>
                             <div class="actions">
                                <a href="<?php echo $_product->getProductUrl() ?>" class="link_details"><?php echo $this->__('Details') ?></a>
                            </div>
                        </div>
                          <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                        </div>
                    </td>
                <?php endforeach; ?>
                </tr>
            </table>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    </div>
<?php endif; ?>