<?php
$_productCollection = Mage::getModel('catalog/product')->getCollection();
$_productCollection->addAttributeToSelect('*')
                   ->addFieldToFilter('visibility', array(
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                   )) 
                   ->addFinalPrice()
                   ->getSelect()
                   ->where('price_index.final_price < price_index.price');
 
Mage::getModel('review/review')->appendSummary($_productCollection);
 
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="page-title category-title">
            <h1>Special</h1>
    </div>
    <div class="category-products">
            <?php $_iterator = 0; ?>
            <ul class="products-grid row" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item col-xs-12 col-sm-4">
                        <div class="grid_wrap">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(228) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                        <div class="product-shop">
                                <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                                    <div class="desc_grid"><?php $small_getDescription = strip_tags($_product->getShortDescription());
                                 if (strlen($small_getDescription) < 70) echo($small_getDescription);
                                 else { echo mb_substr($small_getDescription, 0, 70,'UTF-8').'...';} ?></div>
                                    <?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>


                             <div class="actions">
                                <?php if($_product->isSaleable()): ?>
                                    <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link_cart"><strong><i class="fa fa-shopping-cart"></i></strong><span><?php echo $this->__('Add to Cart') ?></span></a>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" class="link_details"><?php echo $this->__('Details') ?></a>
                                <!-- <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" rel="tooltip" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a  title="<?php echo $this->__('Add to Compare') ?> " href="<?php echo $_compareUrl ?>" rel="tooltip" class="link-compare "><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul> -->
                            </div>
                        </div>
                          <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                            <div class="label-product">             
                                <?php if($_product->getData('new')){echo '<span class="new"><strong>'.$this->__('New').'</strong></span>';  }?>
                                <?php if($_product->getData('sale')){echo '<span class="sale"><strong>'.$this->__('Sale').'</strong></span>';  }?>
                            </div>
                            </div>
                    </li>
                <?php endforeach; ?>
            </ul>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    </div>
<?php endif; ?>