<?php

/**
 * Created by PhpStorm.
 * User: vjcspy
 * Date: 7/21/15
 * Time: 2:30 PM
 */
class SM_XPos_Block_Adminhtml_Cache extends Mage_Adminhtml_Block_Cache
{
    /**
     * Internal constructor, that is called from real constructor
     *
     */
    protected function _construct()
    {

        $message = Mage::helper('core')->__('Cache X-POS may contain additional data. Are you sure that you want flush it?');
        $this->_addButton('flush_xpos', array(
            'label'   => Mage::helper('core')->__('Flush X-POS Cache'),
            'onclick' => 'confirmSetLocation(\'' . $message . '\', \'' . $this->getFlushXPosStorageUrl() . '\')',
            'class'   => 'delete',
        ));
        parent::_construct(); // TODO: Change the autogenerated stub

    }

    public function getFlushXPosStorageUrl()
    {
        return $this->getUrl('*/*/flushXPosCache');
    }


}
