<?php

/**
 * Created by PhpStorm.
 * User: vjcspy
 * Date: 7/18/15
 * Time: 5:52 PM
 */
class SM_XPos_Model_Adminhtml_Sales_Order_Create extends Mage_Adminhtml_Model_Sales_Order_Create
{
    /**
     * Create new order
     *
     * @return Mage_Sales_Model_Order
     */
    public $_realTimeProduct = null;

    public function createOrder()
    {

        $order = parent::createOrder(); // TODO: Change the autogenerated stub
        $orderItems = $order->getAllItems();
        //$storeId = $order->getStoreId();
        foreach ($orderItems as $item) {
            $productId = $item->getProductId();
            $this->getRealTimeProduct()->proNeedReload($productId, null);
        }

        return $order;
    }

    public function getRealTimeProduct()
    {
        if (is_null($this->_realTimeProduct)) {
            $this->_realTimeProduct = Mage::helper('xpos/realTimeProduct');
        }

        return $this->_realTimeProduct;

    }

}
