<?php /* @var $this SM_XPos_Block_Adminhtml_Index_StoreView_StoreVIew */ ?>
<?php $dataStoreView = $this->loadStoreView(); ?>
<div id="till_popup1" class="popup xpos_store_view">
    <div class="panel_block" id="till-chooser">
        <h4><?php echo $this->__("Choose Store") ?></h4>
        <ul id="till_list">
            <?php if (count($dataStoreView) > 0) { ?>
                <?php foreach ($dataStoreView as $storeValue => $text) { ?>
                    <li id="store_<?php echo $text['value']; ?>"><a
                            onclick="setStore('<?php echo $text['value']; ?>','<?php echo $text['label']; ?>')"
                            href="javascript:"><?php echo $text['label'] ?></a></li>
                <?php } ?>

            <?php } else { ?>
                <li><span class="no-store no-hover"><?php echo $this->__("Please add a store") ?></span></li>
            <?php } ?>
        </ul>
    </div>
</div>


<script>

    //    jQuery(document).ready(function() {
    //        var isTillEnable = <?php //echo Mage::helper('xpos/configXPOS')->getEnableTill(); ?>//;
    //
    //        if(isTillEnable == 1 && $.jStorage.get('xpos_till') != null){
    //            jQuery('#till_name').html($.jStorage.get('xpos_till').till_name);
    //            jQuery('#till_id').val($.jStorage.get('xpos_till').till_id);
    //            order.tillId = jQuery('#till_id').val();
    //        }
    //    });

    function show_popup_store() {
        if ($.jStorage.get('xpos_store') == null) {

            jQuery('.xpos_store_view').bPopup({
                modalClose: false,
                escClose: false,
                opacity: 0.6,
                speed: 450,
                transition: 'slideBack',
                positionStyle: 'fixed' //'fixed' or 'absolute'
            });
        } else if (window.isWarehouseIntegrate && $.jStorage.get('xpos_warehouse') == null) {
            var storeView = $.jStorage.get('xpos_store');
            var url1 = changeStoreViewUrl + "?storeId=" + storeView.id;
            var url = url1.replace("?___SID=U", "");
            url = url.replace("?___SID=S", "");
            jQuery.getJSON(url, function (json) {
                dataFromServer = json;
                if (dataFromServer.status != 'true') {
                    iLog('set Store Session Failed', null, 5);
                } else {
                    iLog('set Store view OK');
                    order.storeId = storeView.id;
                    jQuery('#warehouse_name').html(storeView.store_name);
                    window.multiStoreView.setData(storeView.id, storeView.store_name);
                    window.multiStoreView.setPriceFormat(json.priceFormat);
                    window.multiStoreView.getDataProOp();
                    if (json.needReload == true) {
                        location.reload(true);
                    }
                    loadProductData();
                }
            });
            show_popup_warehouse();
        } else {
            show_popup_till();
            var storeView = $.jStorage.get('xpos_store');
            var url1 = changeStoreViewUrl + "?storeId=" + storeView.id;
            var url = url1.replace("?___SID=U", "");
            url = url.replace("?___SID=S", "");
            jQuery.getJSON(url, function (json) {
                dataFromServer = json;
                if (dataFromServer.status != 'true') {
                    iLog('set Store Session Failed', null, 5);
                } else {
                    iLog('set Store view OK');
                    order.storeId = storeView.id;
                    jQuery('#store_name').html(storeView.store_name);
                    window.multiStoreView.setData(storeView.id, storeView.store_name);
                    window.multiStoreView.setPriceFormat(json.priceFormat);
                    window.multiStoreView.getDataProOp();
                    if (json.needReload == true) {
                        location.reload(true);
                    }
                    loadProductData();
                }
            });
        }
    }

    function setStore(id, name) {
        displayLoadingMask();
//        jQuery('#till_name').html(name);
        var xpos_store = {
            id: id,
            store_name: name
        };
        jQuery('.xpos_store_view').bPopup().close();
        window.multiStoreView.changeStoreViewXpos(xpos_store);
    }

    function xpos_change_store() {
//        transactionMoneyLoaded = false;
//        jQuery('#till_name').html("Default");

        if (confirm('<?php echo $this->__("Current order will be lost?") ?>')) {

            if (isOnline()) {
                $.jStorage.deleteKey('xpos_store');
                show_popup_store();
                jQuery.ajax({
                    aasync: false,
                    url: '<?php echo $this->getUrl('*/*/clear') ?>'
                });
            } else {
                return true;
            }
        }

    }

</script>
<script>
</script>
