<?php  $_order = $this->getCreditmemo()->getOrder() ?>
<input type="hidden" id='xpos-order' value="<?php echo $_order->getId()?>"/>
<div class="messages-grid" style="display: none;"><ul class="messages"><li class="success-msg"><ul><li><span class="detail-messages"></span></li></ul></li></ul></div>
<form id="edit_form_creditmemo" method="post" action="<?php echo $this->getSaveUrl() ?>">
    <?php echo $this->getBlockHtml('formkey')?>

    <?php echo $this->getChildHtml('order_info') ?>

    <?php if (!$_order->getIsVirtual()): ?>
    <div class="box-left">
        <?php else: ?>
        <div class="box-right">
            <?php endif; ?>
            <!--Billing Address-->

        </div>
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="box-right">
                <!--Shipping Address-->

            </div>
        <?php endif; ?>
        <div class="clear"></div>

        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Items to Refund') ?></h4>
            </div>
        </div>
        <div id="creditmemo_item_container">
            <?php echo $this->getChildHtml('order_items') ?>
        </div>
</form>
