<?php
/**
	THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
	INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
	PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
	LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
	TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
	OR OTHER DEALINGS IN THE SOFTWARE.


	* ScarletRed_Packingslips module
	* 
	* @category   	ScarletRed
	* @package		ScarletRed_Packingslips
	* @version		1.0.1
	* @author		Lee Walker
	* @copyright  	ScarletRed Copyright (c) 2014
**/

class ScarletRed_Packingslips_Helper_Data extends Mage_Core_Helper_Abstract
{

}