<?php if ($this->canUseCredit()): ?>
<div style="margin-bottom: 3px">
    <input id="p_method_use_credit" value="1" name="payment[use_credit]" type="checkbox" title="<?php echo $this->__('Store Credit') ?>" onclick="" <?php if ($this->getUseCredit()): ?>checked<?php endif; ?> />
    <label for="p_method_use_credit">
        <?php echo $this->__('Use Store Credit (%s available)', $this->formatPrice($this->getBalance())) ?>
    </label>
    
    <script type="text/javascript">
        function toggleUseCredit()
        {
            value = ($('p_method_use_credit').checked ? 1 : 0);
            var data = {};
            data['payment[use_credit]'] = value;

            order.loadArea(['totals', 'billing_method'], true, data);
        }
        Event.observe($('p_method_use_credit'), 'click', toggleUseCredit);
        Event.observe(document, 'dom:loaded', toggleUseCredit);
    </script>
</div>
<?php endif ?>
