<?php /* @var $this SM_XPos_Block_Adminhtml_Override_Coupons */ ?>
<?php $isGiftCard = false;?>
<div class="checkout-item no-hover">
    <div class="entry-edit">
        <div class="entry-edit-head" id="group-coupon-code-heading">
            <h4 class="icon-head"
                id="group-coupon-code-h4"><?php echo $this->__("Apply Coupon Code") ?></h4>
            <span class="ui-icon-off-coupon"></span>
        </div>
        <fieldset class="np content">
            <div class="content" id="group-coupon-code-content">
                <p>
                    <?php if ($this->getCouponCode()) { ?>
                        <input type="text" class="input-text" id="coupons:code"
                               value="<?php echo $this->getCouponCode() ?>" name="coupon_code"
                               style="width:200px; padding: 4px 8px" disabled/>&nbsp;
                        <?php echo $this->getButtonHtml($this->__("Remove"), "order.applyCoupon('');") ?>
                    <?php } else { ?>
                        <input type="text" class="input-text" id="coupons:code" value="" name="coupon_code"
                               style="width:200px; padding: 4px 8px"/>&nbsp;
                        <?php echo $this->getButtonHtml($this->__("Apply"), 'order.applyCoupon($F(\'coupons:code\'));showOrderMessBox();') ?>
                    <?php } ?>
                </p>
            </div>
        </fieldset>
    </div>
</div>
<script>

    <?php if ($this->getCouponCode()) { ?>
    var coupon_code = jQuery("[name='coupon_code']").val();
    jQuery("#discount_detail").html("Coupon : " + coupon_code);
    <?php }else{ ?>
    jQuery("#discount_detail").html("<?php echo $this->__("No Discount") ?>");
    <?php } ?>

    function showOrderMessBox() {
        //jQuery('#order-message').show();
    }
</script>

<!--TODO: integrate Magestore RP-->
<?php
if (Mage::getModel('xpos/integrate')->isIntegrateRp()) { ?>
    <!--@Add RP-->
    <div class="checkout-item no-hover">
        <div class="entry-edit">
            <div class="entry-edit-head" id="group-rp-code-heading">
                <h4 class="icon-head"
                    id="group-rp-code-h4"><?php echo $this->__("Apply Reward Points") ?></h4>
                <span class="ui-icon-off-coupon"></span>
            </div>
            <fieldset class="np content">
                <div class="content" id="group-rp-code-content">
                    <!--Begin here-->
                    <?php if ($this->enableReward()): ?>
                        <?php $_sliderRules = $this->getSliderRules() ?>
                        <?php $_checkboxRules = $this->getCheckboxRules() ?>
                        <?php
                        /** @var $_pointHelper Magestore_RewardPoints_Helper_Point */
                        $_pointHelper = $this->getPointHelper();
                        $_pointName = $_pointHelper->getPluralName();
                        ?>

                        <?php if (count($_sliderRules) || (count($_checkboxRules))): ?>
                            <div class="entry-edit box-right" id="admin_rewardpoints_rules">
                                <div class="entry-edit-head">
                                    <h4 class="icon-head">
                                        <?php echo $this->__('Use Customer Reward Points') ?>
                                        (<?php echo Mage::helper('rewardpoints/customer')->getBalanceFormated() ?>)
                                    </h4>
                                </div>
                                <fieldset class="np">
                                    <div class="content">
                                        <div id="cart-rewards-form">
                                            <dl class="form-list rewards-sales-rules">
                                                <?php if (count($_sliderRules)): ?>
                                                    <?php $_sliderData = $this->getSliderData() ?>
                                                    <dt>
                                                        <label><?php echo $this->__('Choose how many points to spend') ?>
                                                            :</label>
                                                    </dt>
                                                    <dd>
                                                        <?php if (count($_sliderRules) == 1): ?>
                                                            <?php $_rule = current($_sliderRules) ?>
                                                            <input id="reward_sales_rule" name="reward_sales_rule"
                                                                   type="hidden" value="<?php echo $_rule->getId() ?>"/>
                                                            <span>
                        <?php if ($_rule->getId() == 'rate'): ?>
                            <?php echo '   ' . $this->__('Each %s get %s discount', $_pointHelper->format($_rule->getPointsSpended(), $this->getStore()), $this->formatDiscount($_rule)) ?>
                        <?php else: ?>
                            <?php echo $this->escapeHtml($_rule->getName()) ?>
                            (<?php echo $this->__('With %s', $_pointHelper->format($_rule->getPointsSpended(), $this->getStore())) ?>)
                        <?php endif ?>
                    </span>
                                                        <?php else: ?>
                                                            <div class="reward-rules">
                                                                <span><?php echo $this->__('Use Reward Points') ?>
                                                                    :</span>
                                                                <select id="reward_sales_rule" name="reward_sales_rule"
                                                                        class="input-select">
                                                                    <?php foreach ($_sliderRules as $_rule): ?>
                                                                        <option
                                                                            value="<?php echo $_rule->getId() ?>"<?php if ($_rule->getId() == $_sliderData->getRuleId()): ?> selected="selected"<?php endif ?>>
                                                                            <?php if ($_rule->getId() == 'rate'): ?>
                                                                                <?php echo $this->__('Each %s get %s discount', $_pointHelper->format($_rule->getPointsSpended(), $this->getStore()), $this->formatDiscount($_rule)) ?>
                                                                            <?php else: ?>
                                                                                <?php echo $this->escapeHtml($_rule->getName()) ?>
                                                                                (<?php echo $this->__('With %s', $_pointHelper->format($_rule->getPointsSpended(), $this->getStore())) ?>)
                                                                            <?php endif ?>
                                                                        </option>
                                                                    <?php endforeach ?>
                                                                </select>
                                                            </div>
                                                        <?php endif ?>
                                                        <div id="rewardpoints-needmore-msg" style="display: none;">
                                                            <?php echo $this->__('Customer not enough points to spend') ?>
                                                        </div>
                                                        <div id="rewardpoints-slider-container">
                                                            <div id="rewardpoints-slider">
                                                                <div id="rewardpoints-slider-zoom-out"><img
                                                                        src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>"
                                                                        alt="<?php echo $this->__('Zoom Out') ?>"
                                                                        title="<?php echo $this->__('Zoom Out') ?>"/>
                                                                </div>
                                                                <div id="rewardpoints-track"
                                                                     style="background-image: url('<?php echo $this->getSkinUrl('images/rewardpoints/reward_rule.gif') ?>')">
                                                                    <div id="rewardpoints-handle"
                                                                         style="background-image: url('<?php echo $this->getSkinUrl('images/magnifier_handle.gif') ?>')"></div>
                                                                </div>
                                                                <div id="rewardpoints-slider-zoom-in"><img
                                                                        src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>"
                                                                        alt="<?php echo $this->__('Zoom In') ?>"
                                                                        title="<?php echo $this->__('Zoom In') ?>"/>
                                                                </div>
                                                            </div>
                                                            <div class="rewardpoints-slider-input">
                                                                <div class="input-point">
                            <span>
                                <?php echo $this->__('You will spend') ?>
                                <input type="text" class="input-text" id="reward_sales_point" name="reward_sales_point"
                                       value="0"/>
                                <?php echo $_pointName ?>
                            </span>
                                                                </div>
                                                                <div class="input-max">
                                                                    <input type="checkbox" id="reward_max_points_used"/>
                                                                    <label for="reward_max_points_used">
                                                                        <?php echo $this->__('Maximize discount with points') ?>
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </dd>
                                                    <script type="text/javascript">
                                                        rewardSliderRules = <?php echo $this->getRulesJson($_sliderRules) ?>;
                                                        currentPointUsed = <?php echo $_sliderData->getUsePoint() ? $_sliderData->getUsePoint() : '0' ?>;
                                                        currentRuleUsed = $('reward_sales_rule').value;
                                                        // Initial Variables
                                                        // $('rewardpoints-slider-container').show();
                                                        rewardSlider = new RewardPointsSlider(
                                                            'reward_sales_point',
                                                            'rewardpoints-track',
                                                            'rewardpoints-handle',
                                                            'rewardpoints-slider-zoom-out',
                                                            'rewardpoints-slider-zoom-in',
                                                            ''
                                                        );
                                                        rewardSlider.changePointCallback = changePointCallback;
                                                        rewardSlider.changeUseMaxpointEvent('reward_max_points_used');
                                                        rewardSlider.manualChangePointEvent('reward_sales_point');
                                                        rewardSlider.changeRule = function (event) {
                                                            var ruleId = event.element().value;
                                                            if (ruleId) {
                                                                currentRuleOptions = rewardSliderRules[ruleId];
                                                                switch (currentRuleOptions.optionType) {
                                                                    case 'needPoint':
                                                                        showRewardInfo('rewardpoints-needmore-msg');
                                                                        break;
                                                                    case 'slider':
                                                                        showRewardInfo('rewardpoints-slider-container');
                                                                        this.applyOptions(currentRuleOptions.sliderOption);
                                                                        break;
                                                                }
                                                            } else {
                                                                showRewardInfo('');
                                                            }
                                                        };
                                                        rewardSlider.changeRuleEvent = function (el) {
                                                            Event.observe($(el), 'change', this.changeRule.bind(this));
                                                        };
                                                        rewardSlider.changeRuleEvent('reward_sales_rule');
                                                        // $('rewardpoints-slider-container').hide();
                                                        uniqueAjax = new RewardPointsAjax('<?php echo $this->getUrl('rewardpoints/adminhtml_checkout/changePoint') ?>');

                                                        disableRewardAjax = true;
                                                        changeRewardSalesRule($('reward_sales_rule'));
                                                        disableRewardAjax = true;
                                                        rewardSlider.manualChange(<?php echo $_sliderData->getUsePoint() ? $_sliderData->getUsePoint() : '0' ?>);
                                                        disableRewardAjax = false;
                                                    </script>
                                                <?php endif ?>
                                                <?php if (count($_checkboxRules)): ?>
                                                    <?php $_checkedData = $this->getCheckedData() ?>
                                                    <dt>
                                                        <?php if (count($_sliderRules)): ?>
                                                            <label><?php echo $this->__('More ways to spend points') ?>
                                                                :</label>
                                                        <?php else: ?>
                                                            <label><?php echo $this->__('Choose ways to spend points') ?></label>
                                                        <?php endif ?>
                                                    </dt>
                                                    <dd>
                                                        <ul>
                                                            <?php foreach ($_checkboxRules as $_rule): ?>
                                                                <li>
                                                                    <input type="checkbox"
                                                                           value="<?php echo $_rule->getId() ?>"
                                                                           name="sales_checkbox_rule[]"
                                                                           id="sales_checkbox_rule_<?php echo $_rule->getId() ?>"
                                                                           onclick="checkUseSalesRule(this, '<?php echo $this->getUrl('rewardpoints/adminhtml_checkout/checkboxRule') ?>')"<?php if (in_array($_rule->getId(), $_checkedData)): ?> checked="checked"<?php endif ?> />
                                                                    <label
                                                                        for="sales_checkbox_rule_<?php echo $_rule->getId() ?>"
                                                                        id="reward_rule_label_<?php echo $_rule->getId() ?>">
                                                                        <?php echo $this->__('Spend %s', $_pointHelper->format($_rule->getPointsSpended(), $this->getStore())) ?>
                                                                        <?php echo $this->__('and get %s off', $this->formatDiscount($_rule)) ?>
                                                                    </label>
                                                                </li>
                                                            <?php endforeach ?>
                                                        </ul>
                                                    </dd>
                                                <?php endif ?>
                                            </dl>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>

                            <script type="text/javascript">
                                Event.observe(window, 'load', function () {
                                    if (order) {
//                                        order.loadArea(['totals'], true, {});
                                    }
                                });
                            </script>
                        <?php endif ?>

                    <?php endif // end $this->enableReward() condition
                    ?>
                    <!--end-->
                </div>
            </fieldset>
        </div>
    </div>
<?php } ?>

<!--end Integrate RP-->

<!--TODO: Integrate with WEBTEX GIFTCARD-->
<?php
if (Mage::getModel('xpos/integrate')->isIntegrateWithWebtexGiftCard()) {
    ?>
    <div id="giftCardBlock" class="checkout-item no-hover">
        <div class="entry-edit">
            <div class="entry-edit-head" id="group-giftcard-code-heading">
                <h4 class="icon-head"
                    id="group-giftcard-code-h4"><?php echo $this->__("Apply Gift Card Code") ?></h4>
                <span class="ui-icon-off-giftcard"></span>
            </div>
            <fieldset class="np content">
                <div class="content" id="group-giftcard-code-content">
                    <p>
                        <input type="text" class="input-text" id="giftcards:code" value="" name="giftcards_code"
                               style="width:180px; padding: 4px 8px"/>&nbsp;
                        <?php echo $this->getButtonHtml($this->__("Apply"), 'order.applyWebtexGiftCard($F(\'giftcards:code\'));showOrderMessBox();') ?>
                    </p>
                    <?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>
                    <?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
                    $temp = 0; ?>
                    <?php if ($oGiftCardSession->getActive())
                        foreach ($oGiftCardSession->getFrontOptions() as $k => $v) {
                            $isGiftCard = true;
                            if ($temp) {
                                echo '<br/><br/>';
                            }
                            echo '<b style="padding: 4px 28px;font-size: 13px;vertical-align: middle;font-weight: bold">' . '- ' . $currencySymbol . $v['applied'] . ' ' . $this->__('applied from Gift Card') . ' ' . $v['code'] . '<br>';
                            echo '<span style="font-size: 13px;padding: 4px 28px;font-weight: lighter">' . $this->__('Remaining card balance') . ': ' . $currencySymbol . $v['remaining'] . '. (<a style="display:inline;padding-left:0px" onclick="order.removeWebtexGiftCard(' . $k . ');showOrderMessBox();">' . $this->__('Remove') . '</a>)' . '</span>';
                            $temp = 1;
                        }
                    ?>
                </div>
            </fieldset>
        </div>
    </div>
    <?php
}
?>

<!--TODO: integrate with Mage world RewardPoints-->
<?php if (Mage::getModel('xpos/integrate')->isIntegrateMageWorldRp()) { ?>
    <div class="checkout-item no-hover">
        <div class="entry-edit">
            <!--            <div class="entry-edit-head" id="group-mwrp-code-heading">-->
            <!--                <h4 class="icon-head"-->
            <!--                    id="group-mwrp-code-h4">-->
            <?php //echo $this->__("Add Reward points") ?><!--</h4>-->
            <!--                <span class="ui-icon-off-coupon"></span>-->
            <!--            </div>-->
            <fieldset class="np content">
                <div class="content" id="group-mwrp-code-content">


                    <?php
                    $store_id = $this->getStoreId();
                    $rate = $this->getRate($store_id); ?>
                    <div class="entry-edit box-right">
                        <div class="entry-edit-head">
                            <h4 class="icon-head"
                                style="font-size: 14px"><?php echo $this->__('Reward points (Use maximum <b>%s</b>)', $this->getMaxPointToCheckOut()); ?></h4>
                        </div>
                        <fieldset class="np">
                            <div class="content">
                                <ul id="mw_reward_accordion" style="display: none;">
                                    <li class="mw_reward_section">
                                        <div <?php if (!sizeof($this->getRewardPointsRule())) echo "style=\"display:none\""; ?> >
                                            <span id="reward-points-rules-title"
                                                  style="color: #0A263C;line-height: 1.5;"><?php echo $this->__("You will be awarded <b>%s</b>", $this->getEarnPointShow() . " ") ?>
                                                <a id="mw_view" class="mw_reward_title"
                                                   style="color: #DC6809 !important;font-weight: bold"
                                                   href="#"><?php echo $this->__('(Details)'); ?></a></span></div>
                                        <div id="reward-points-rules" class="mw_reward_toggle">
                                            <?php foreach ($this->getRewardPointsRule() as $rule): ?>
                                                <div
                                                    style="width:100%;font-size: 11px; margin: 0 0 5px 0; overflow: hidden;">
                                                    <div
                                                        style="float:left; width:258px"><?php echo $this->__('<span style="float: left;">+</span> <div style="margin: 0px 0px 0px 10px;">%s %s</div>', ($rule['qty'] > 1 ? $rule['qty'] . " x" : ""), $rule['message']); ?></div>
                                                </div>
                                            <?php endforeach; ?>
                                        </div>
                                    </li>
                                </ul>

                                <div
                                    style="font-size: 13px;padding: 4px 28px;font-weight: lighter"><?php echo $this->__("You have <b>%s</b> available (<b>%s</b> = <b>%s</b>)", $this->getCurrentRewardPoints(), Mage::helper('rewardpoints')->formatPoints($rate[0], $store_id), $this->formatMoney($rate[1])) ?></div>

                                <p><input id="mw_rewardpoint_add_input" type="text" class="input-text validate-digits"
                                          style="width:180px" onfocus="checkCheckPoint()"/>&nbsp;
                                    <button onclick="applyMwRewardPoint()" type="button" value="" class="scalable">
                                        <span><span><span><?php echo $this->__('Add Reward points'); ?></span></span></span>
                                    </button>
                                </p>
                                <?php if ($points = $this->getRewardPoints()) { ?>
                                    <p>
                                        <strong
                                            style="font-size: 13px;padding: 4px 28px;font-weight: lighter"><?php echo Mage::helper('rewardpoints')->formatPoints($points, $store_id); ?></strong>
                                        [<a style="display: inline;padding-left: 0px;" href="#"
                                            onclick="removeMwRewardPoint('<?php echo $points; ?>'); return false;"
                                            title="<?php echo $this->__('Remove'); ?>"><?php echo $this->__('Remove'); ?></a>]
                                    </p>
                                <?php } ?>

                                <div
                                    style="font-size: 13px;padding: 4px 28px;font-weight: bold"><?php echo $this->__('Use maximum <b>%s</b>', $this->getMaxPointToCheckOut()); ?></div>
                            </div>
                        </fieldset>
                    </div>

                    <script type="text/javascript">
                        //<![CDATA[

                        accordion = new Accordion('mw_reward_accordion', {startHidden: false});
                        document.observe('dom:loaded', function () {
                            accordion = new Accordion('mw_reward_accordion', {startHidden: false});

                        });
                        //]]>
                    </script>
                    <script type="text/javascript">
                        function removeMwRewardPoint(code) {
                            window.isApplyingRp = true;
                            var data = {};
                            data['mw_rewardpoint_remove'] = code;
                            order.loadArea(['coupons', 'totals'], true, data);
                        }

                        function applyMwRewardPoint() {
                            window.isApplyingRp = true;
                            var code = $('mw_rewardpoint_add_input').value;
                            var data = {};
                            data['mw_rewardpoint_add'] = code;
                            order.loadArea(['coupons', 'totals'], true, data);
                        }

                        function checkCheckPoint() {
                            jQuery("#mw_rewardpoint_add_input").keydown(function (e) {
                                // if press Enter -> will blur
                                if (e.keyCode == 13) {
                                    jQuery(this).blur();
                                    return
                                }
                                // Allow: backspace, delete, tab, escape, enter and .
                                if (jQuery.inArray(e.keyCode, [46, 8, 9, 27, 110, 190]) !== -1 ||
                                        // Allow: Ctrl+A, Command+A
                                    (e.keyCode == 65 && ( e.ctrlKey === true || e.metaKey === true ) ) ||
                                        // Allow: home, end, left, right, down, up
                                    (e.keyCode >= 35 && e.keyCode <= 40)) {
                                    // let it happen, don't do anything
                                    return;
                                }
                                // Ensure that it is a number and stop the keypress
                                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105) || e.keyCode == 190) {
                                    e.preventDefault();
                                }
                            }).blur(function () {
                                var maxValue = '<?php echo $this->getMaxPointToCheckOut(false); ?>';
                                currentValue = jQuery("#mw_rewardpoint_add_input").val();
                                if (parseFloat(currentValue) > parseFloat(maxValue) || parseFloat(currentValue) ==0) {
                                    jQuery("#mw_rewardpoint_add_input").val(maxValue);
                                }
                            });
                        }
                    </script>


                </div>
            </fieldset>
        </div>
    </div>
<?php } ?>
<script>
    jQuery(document).ready(function () {
        <?php if($isGiftCard){ ?>
        jQuery('#discount_detail').html('Gift Card');
        <?php }?>
    });
</script>

<!--TODO: Integrate with Rack Point-->


<?php if (Mage::getModel('xpos/integrate')->isIntegrateRackRp()) { ?>
    <?php
    $currentBalance = $this->getCurrentBalance();
    $quote = $this->getQuote();
    $requirePoint = $this->getMinRequiredPoints();
    if ($this->getUsedPoint() <= 0) {
        $currentPoint = $requirePoint;
        $currentPoint = min($currentPoint, $currentBalance->getPoint());
    } else {
        $currentPoint = $this->_getSession()->getPointUsed();
    }
    $pointInput = '<input type="text" class="validate-digits-range digits-range-1-' . min($currentBalance->getPoint(), $requirePoint) . ' validate-greater-than-zero validate-digits" name="payment[used_point]" id="payment_used_point_input" value="' . $currentPoint . '" />';
    $minRequiredPoint = (float)Mage::getStoreConfig('rackpoint/config/min_required_point');
    ?>
    <?php if ($currentBalance->getPoint() > 0): ?>
        <div class="checkout-item no-hover">
            <div class="entry-edit">
                <div class="entry-edit-head" id="group-rackrp-code-heading">
                    <h4 class="icon-head"
                        id="group-rackrp-code-h4"><?php echo $this->__("Apply Reward Point") ?></h4>
                    <span class="ui-icon-off-rackrp"></span>
                </div>
                <label style="font-size: 13px;padding: 4px 28px;font-weight: bold; "
                       for="payment_use_point"><?php echo $this->__('Would you like to use point to pay for this order?') ?>
                    <?php if ($minRequiredPoint > 0): ?>
                    <div style="font-size: 13px;padding: 4px 28px;font-weight: bold">
                        (<?php echo $this->__('Maximum %s points to pay for this order, and Please enter point amount greater than %s points.', number_format(min($currentBalance->getPoint(), $requirePoint), 0), number_format($minRequiredPoint, 0)) ?></div>
                    )</label>
                <?php else: ?>
                <div style="font-size: 13px;padding: 4px 28px;font-weight: bold">
        (<?php echo $this->__('Use maximum %s points to pay for this order.', number_format(min($currentBalance->getPoint(), $requirePoint), 0)) ?>)</div></label>
        <?php endif ?>
                <fieldset class="np content">
                    <div class="content" id="group-rackrp-code-content">
                        <p>
                            <input type="text" class="input-text" id="rackrp:code"
                                   value="<?php echo $quote->getPointUsed() ?>" name="rackrp_code"
                                   style="width:200px; padding: 4px 8px"/>&nbsp;
                            <?php echo $this->getButtonHtml($this->__("Apply"), 'order.applyRackRp($F(\'rackrp:code\'));showOrderMessBox();') ?>
                        </p>
                </fieldset>
            </div>
        </div>
    <?php endif ?>
    <script>

    </script>

<?php } ?>


<!--TODO: Integrate with Gift Voucher (Gift Card Magento)-->

<?php
if (Mage::getModel('xpos/integrate')->isIntegrateWithGiftVoucher()):
?>
    <div id="giftVoucherBlock" class="checkout-item no-hover">
        <div class="entry-edit">
            <div class="entry-edit-head" id="group-giftvoucher-code-heading">
                <h4 class="icon-head"
                    id="group-giftvoucher-code-h4"><?php echo $this->__("Apply Gift Card Code") ?></h4>
                <span class="ui-icon-off-giftcard"></span>
            </div>
            <fieldset class="np content">
                <div class="content" id="group-giftvoucher-code-content">
                    <p>
                        <input type="text" class="input-text" id="giftvoucher:code" value="" autocomplete="off" name="giftvoucher_code"
                               style="width:200px; padding: 4px 8px"/>&nbsp;
                        <?php echo $this->getButtonHtml($this->__("Apply"), 'order.applyGiftVoucher($F(\'giftvoucher:code\'));showOrderMessBox();') ?>
                    </p>
                    <?php $discounts = $this->getGiftVoucherDiscount();?>
<?php if (count($discounts)): ?>
    <?php foreach ($discounts as $code => $discount): ?>
        <?php
        if($discount <= 0) continue; ?>
        <p>
            <b style="padding: 4px 28px;font-size: 13px;vertical-align: middle;color: #008000;"> <?php echo Mage::helper('giftvoucher')->getHiddenCode($code) ?>(<span style="color: #143d52"><?php echo Mage::helper('checkout')->formatPrice($discount) ?></span>)
                <a style="display:inline;padding-left:0px; font-size: 10px;" onclick="order.removeGiftVoucher('<?php echo $code;?>');showOrderMessBox();"><?php echo $this->__('Remove');?></a>
                </b>
        </p>

    <?php endforeach;?>
    <script>
        jQuery(document).ready(function () {
            jQuery('#discount_detail').html('Gift Voucher');
        });
    </script>
<?php endif;?>
                </div>
            </fieldset>
        </div>
    </div>
<?php
endif;
?>