<?php
/*
 * @var SM_XPos_Block_Adminthml_XPos_Receipt_Items $this
 */
?>

<div class="items-view" style="<?php echo $this->getHtmlSeparatorStyle(); ?>">
    <table>
        <thead>
        <tr>
            <th class="item-name" data-metadata="item-name" align="left"><?php echo Mage::helper('xpos')->__('ITEM'); ?></th>
            <th data-metadata="qty"><?php echo Mage::helper('xpos')->__('Qty'); ?></th>
            <th class="price-container" data-metadata="price"><?php echo Mage::helper('xpos')->__('PRICE'); ?></th>
            <th class="tax" data-metadata="tax-amount"><?php echo Mage::helper('xpos')->__('TAX'); ?></th>
            <th class="row-total" data-metadata="row-total" align="right"><?php echo Mage::helper('xpos')->__('SUBTOTAL'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php if ($this->getRequest()->getParam('preview') != null): ?>
            <!--For previewing-->
            <tr>
                <td class="item-name" data-metadata="item-name" align="left">Product Item Preview #1 <span class="sku">SKU!123</span></td>
                <td data-metadata="qty">0</td>
                <td class="price-container" data-metadata="price"><?php echo Mage::helper('core')->currency(0, true, false); ?></td>
                <td class="tax" data-metadata="tax-amount"><?php echo Mage::helper('core')->currency(0, true, false); ?></td>
                <td class="row-total" data-metadata="row-total" align="right"><?php echo Mage::helper('core')->currency(0, true, false); ?></td>
            </tr>
            <tr>
                <td class="item-name" data-metadata="item-name" align="left">Product Item Preview #2 <span class="sku">SKU!223</span></td>
                <td data-metadata="qty">0</td>
                <td class="price-container" data-metadata="price"><?php echo Mage::helper('core')->currency(0, true, false); ?></td>
                <td class="tax" data-metadata="tax-amount"><?php echo Mage::helper('core')->currency(0, true, false); ?></td>
                <td class="row-total" data-metadata="row-total" align="right"><?php echo Mage::helper('core')->currency(0, true, false); ?></td>
            </tr>
        <?php endif; ?>
        <?php foreach($this->getCreditmemo()->getAllItems() as $_item): ?>
            <?php if ($_item->getOrderItem()->getParentItem()) {
                continue;
            } ?>
                <tr>
                    <td class="item-name" data-metadata="item-name" align="left">
                        <?php echo $_item->getName(); ?>
                        <span class="sku"><?php echo $_item->getSku(); ?></span>
                    </td>
                    <td data-metadata="qty"><?php echo floatval($_item->getQty()); ?></td>
                    <td class="price-container" data-metadata="price">
                        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
                            <?php echo $this->getOrder()->formatPrice($_item->getData('price')); ?>
                        <?php endif; ?>
                        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
                            <?php echo $this->getOrder()->formatPrice($_item->getData('price_incl_tax')); ?>
                        <?php endif; ?>
                    </td>
                    <td class="tax" data-metadata="tax-amount"><?php echo $this->getOrder()->formatPrice($_item->getData('tax_amount')); ?></td>
                    <td class="row-total" data-metadata="row-total" align="right">
                        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
                            <?php echo $this->getOrder()->formatPrice($_item->getData('row_total')); ?>
                        <?php endif; ?>
                        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
                            <?php echo $this->getOrder()->formatPrice($_item->getData('row_total_incl_tax')); ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr style="text-transform: uppercase;font-size: 6pt;text-align: left;">
                    <td colspan="5" style="padding: 0">
                        <span style="margin-left: 5px">State Tax:<?php echo $this->getOrder()->formatPrice($_item->getData('statetax')); ?></span>
                        <span style="margin-left: 5px">County Tax:<?php echo $this->getOrder()->formatPrice($_item->getData('countrytax')); ?></span>
                        <span style="margin-left: 5px">City Tax:<?php echo $this->getOrder()->formatPrice($_item->getData('citytax')); ?></span>
                    </td>
                </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
