<?php
/**
* @var SM_XPos_Block_Adminhtml_XPos_CreditMemo_Totals $this
*/
?>

<div class="total-zone">
    <table>
        <tbody>
            <tr>
                <td><?php echo $this->helper('sales')->__('Subtotal') ?></td>
                <td align="right"><strong><?php echo $this->getSubtotal(); ?></strong></td>
            </tr>
            <tr>
                <td><?php echo $this->helper('sales')->__('Shipping') ?></td>
                <td align="right"><strong><?php echo $this->getShippingAmount(); ?></strong></td>
            </tr>
            <tr>
                <td><?php echo $this->helper('sales')->__('Adjustment Refund') ?></td>
                <td align="right"><strong><?php echo $this->getAdjustmentRefund(); ?></strong></td>
            </tr>
            <tr>
                <td><?php echo $this->helper('sales')->__('Adjustment Fee') ?></td>
                <td align="right"><strong><?php echo $this->getAdjustmentFee(); ?></strong></td>
            </tr>
            <tr>
                <td><?php echo $this->helper('sales')->__('Tax') ?></td>
                <td align="right"><strong><?php echo $this->getTax(); ?></strong></td>
            </tr>
            <tr>
                <td><?php echo $this->helper('sales')->__('Total') ?></td>
                <td align="right"><strong><?php echo $this->getGrandTotal(); ?></strong></td>
            </tr>
        </tbody>
    </table>
</div>
<div style="text-align: center">
    <?php echo $this->getTermNCondition (); ?>
</div>
