<?php
/**
 * Created by PhpStorm.
 * User: Le Nam
 * Date: 10/17/14
 * Time: 2:32 PM
 */
?>
<?php
$transfered = formatPostData('transfer_amout');
$diff_total = formatPostData('diff_total');

$xpayment_cashpayment_count = formatPostData('cash_count');
$checkmo_count = formatPostData('check_count');
$ccsave_count = formatPostData('cc_count');
$other_payment_count = formatPostData('other_count');

$cashondelivery_count = formatPostData('cashondelivery_count');
$authorizenet_count = formatPostData('authorizenet_count');
$xpayment_ccpayment_count = formatPostData('xpayment_ccpayment_count');
$xpayment_paypalpayment_count = formatPostData('xpayment_paypalpayment_count');
$xpayment_cc1payment_count = formatPostData('xpayment_cc1payment_count');
$xpayment_cc2payment_count = formatPostData('xpayment_cc2payment_count');
$xpayment_cc3payment_count = formatPostData('xpayment_cc3payment_count');
$xpayment_cc4payment_count = formatPostData('xpayment_cc4payment_count');
$xpayment_bluepaypayment_count = formatPostData('xpayment_bluepaypayment_count');
$xpayment_authorizepayment_count = formatPostData('xpayment_authorizepayment_count');

$report_type = $this->getRequest()->getParam('report_type');

$total_count = $xpayment_cashpayment_count + $checkmo_count + $ccsave_count + $other_payment_count + $cashondelivery_count + $xpayment_ccpayment_count + $authorizenet_count
    + $xpayment_paypalpayment_count + $xpayment_cc1payment_count + $xpayment_cc2payment_count + $xpayment_cc3payment_count
    + $xpayment_cc4payment_count + $xpayment_bluepaypayment_count + $xpayment_authorizepayment_count;

$paymentInfo = Mage::getSingleton('adminhtml/session')->getPaymentInfo();

$transfer = number_format($paymentInfo['xpayment_cashpayment']['previous_transfer'], 2, '.', '');
$discountInfo = Mage::getSingleton('adminhtml/session')->getDiscountInfo();
$total_system = $paymentInfo['other_payment']['grand_order_total']+$paymentInfo['split_total'];
if (Mage::helper('xpos/configXPOS')->getEnableTill() == 1) {
    $till_id = Mage::getSingleton('adminhtml/session')->getTillInfo();
    $tillName = Mage::getModel('xpos/till')->load($till_id)->getData('till_name');
}
if (Mage::helper('xpos/configXPOS')->getIntegrateXmwhEnable()) {
    $warehouse_id = Mage::getSingleton('admin/session')->getWarehouseId();
//            $warehouse_id = Mage::getSingleton('adminhtml/session')->getWarehouseReport();
    $warehouse = Mage::getModel('xwarehouse/warehouse')->load($warehouse_id)->getData('label');
}

if (Mage::helper('xpos/configXPOS')->getEnableCashier() == 1) {
    $cashier_name = $this->getRequest()->getParam('cashier_name');
//            $cashier_id = Mage::getSingleton('adminhtml/session')->getCashierReport();
//            $firstname = Mage::getModel('xpos/user')->load($cashier_id)->getData('firstname');
//            $lastname = Mage::getModel('xpos/user')->load($cashier_id)->getData('lastname');
//            $name = $firstname." ".$lastname;
}
function formatPostData($key)
{
    return number_format(Mage::app()->getRequest()->getParam($key), 2, '.', '');
}

?>
<style>
    .adminhtml-report-printzreport .wrapper {
        min-width: inherit;
    }

    #wrapper table {
        width: 100%;
    }

    #wrapper table td {
        padding: 5px;
    }

    #wrapper table .align_right {
        text-align: right;
    }
</style>
<div id="wrapper">
    <div id="header">
        <h4><?php if (isset($till_id) && $till_id) echo $tillName . '  -'; ?><?php if ($report_type == 'z-report') echo 'End of Day Report'; else echo 'Quick Report'; ?></h4>
        <table>
            <?php if (isset($warehouse)) { ?>
                <tr>
                    <td style="font-weight: bold;">Warehouse</td>
                    <td><?php if ($warehouse) echo $warehouse ?></td>
                </tr>
            <?php } ?>
            <?php if (isset($till_id) && $till_id) { ?>
                <tr>
                    <td style="font-weight: bold;">Till</td>
                    <td><?php echo $tillName ?></td>
                </tr>
            <?php } ?>
            <?php if (isset($cashier_id)) { ?>
                <tr>
                    <td style="font-weight: bold;">Cashier</td>
                    <td><?php echo $cashier_name ?></td>
                </tr>
            <?php } ?>
            <tr>
                <td style="font-weight: bold;">Period</td>
                <td><?php echo date("Y-m-d H:i:s", Mage::getModel('core/date')->timestamp($paymentInfo['other_payment']['previous_time'])); ?></td>
            </tr>
            <tr>
                <td></td>
                <td><?php echo date("Y-m-d H:i:s", Mage::getModel('core/date')->timestamp(time())); ?></td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Orders</td>
                <td><?php echo $paymentInfo['other_payment']['num_order_total'] ?></td>
            </tr>
        </table>
    </div>
    <div id="content">
        <table>
            <tr>
                <td style="font-weight: bold;">Payment Method</td>
                <td style="font-weight: bold;">System</td>
                <?php if ($report_type == 'z-report') { ?>
                    <td style="font-weight: bold;">Count</td>
                <?php } ?>
            </tr>
            <tr>
                <td colspan="3" style="border-bottom: 1px solid #496778;"></td>
            </tr>
            <?php
            if ($paymentInfo)
                foreach ($paymentInfo as $name => $payment) {
                    if ($payment['money_system'] != 0) {
                        ?>
                        <tr>
                        <td><?php echo $payment['payment_name'] ?></td>
                        <td class="align_right"><?php echo number_format($payment['money_system'], 2, '.', ''); ?></td>
                        <?php if ($report_type == 'z-report') { ?>
                            <td class="align_right"><?php
                                $countValue = $name . "_count";
                                echo number_format($$countValue, 2, '.', '');
                                ?></td>
                            <?php
                        }
                    } ?>
                    </tr>
                <?php } ?>
            <tr>
                <td><span style="font-weight: bold;">Included</span></td>
            </tr>
            <tr>
                <td colspan="3" style="border-bottom: 1px solid #496778;"></td>
            </tr>
            <tr>
                <td>Till amount</td>
                <td class="align_right"><?php echo number_format($transfer, 2, '.', '') ?></td>
                <?php if ($report_type == 'z-report') { ?>
                    <td class="align_right"><?php echo number_format($transfer, 2, '.', '') ?></td>
                <?php } ?>
            </tr>

            <tr>
                <td><span style="font-weight: bold;">Not Included</span></td>
            </tr>
            <tr>
                <td colspan="3" style="border-bottom: 1px solid #496778;"></td>
            </tr>
            <?php if ($discountInfo) { ?>
                <tr>
                    <td>Discount</td>
                    <td class="align_right"><?php if ($discountInfo['discount_amount'] > 0) echo number_format($discountInfo['discount_amount'], 2, '.', ''); else echo number_format(-$discountInfo['discount_amount'], 2, '.', '') ?></td>
                    <?php if ($report_type == 'z-report') { ?>
                        <td class="align_right"><?php if ($discountInfo['discount_amount'] > 0) echo number_format($discountInfo['discount_amount'], 2, '.', ''); else echo number_format(-$discountInfo['discount_amount'], 2, '.', '') ?></td>
                    <?php } ?>
                </tr>
            <?php } else { ?>
                <tr>
                    <td>Discount</td>
                    <td class="align_right"><?php echo number_format(0, 2, '.', ''); ?></td>
                    <?php if ($report_type == 'z-report') { ?>
                        <td class="align_right"><?php echo number_format(0, 2, '.', ''); ?></td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <?php if (Mage::getEdition() == "Enterprise") { ?>
                <tr>
                    <td>Vouchers</td>
                    <td class="align_right"><?php if ($discountInfo['voucher'] > 0) echo number_format($discountInfo['voucher'], 2, '.', ''); else echo number_format(-$discountInfo['voucher'], 2, '.', '') ?></td>
                    <?php if ($report_type == 'z-report') { ?>
                        <td class="align_right"><?php if ($discountInfo['voucher'] > 0) echo number_format($discountInfo['voucher'], 2, '.', ''); else echo number_format(-$discountInfo['voucher'], 2, '.', '') ?></td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <?php if ($paymentInfo) { ?>
                <tr>
                    <td>Refunds</td>
                    <td class="align_right"><?php echo number_format($paymentInfo['other_payment']['total_refund'], 2, '.', '') ?></td>
                    <?php if ($report_type == 'z-report') { ?>
                        <td class="align_right"><?php echo number_format($paymentInfo['other_payment']['total_refund'], 2, '.', '') ?></td>
                    <?php } ?>
                </tr>
            <?php } ?>

            <tr>
                <td><span style="font-weight: bold;">Summary</span></td>
            </tr>
            <tr>
                <td colspan="3" style="border-bottom: 1px solid #496778;"></td>
            </tr>
            <tr>
                <td>Total (Incl Tax)</td>
                <td class="align_right"><?php echo number_format($total_system + $transfer, 2, '.', '') ?></td>
                <?php if ($report_type == 'z-report') { ?>
                    <td class="align_right"><?php echo number_format($total_count, 2, '.', '') ?></td>
                <?php } ?>
            </tr>
            <tr>
                <td>Tax Amount</td>
                <td class="align_right"><?php echo number_format($paymentInfo['other_payment']['tax_order_total'], 2, '.', '') ?></td>
                <?php if ($report_type == 'z-report') { ?>
                    <td class="align_right"><?php echo number_format($paymentInfo['other_payment']['tax_order_total'], 2, '.', '') ?></td>
                <?php } ?>
            </tr>
            <?php if ($report_type == 'z-report') { ?>
                <tr>
                    <td>Difference</td>
                    <td></td>
                    <td class="align_right"><?php echo $diff_total ?></td>
                </tr>
                <tr>
                    <td colspan="2">Transfered to Cash Drawer</td>
                    <td class="align_right"><?php echo $transfered ?></td>
                </tr>

            <?php } ?>
        </table>
    </div>

</div>

<script type="text/javascript">
    document.observe("dom:loaded", function () {
        window.print();
        window.onfocus = function () {
            window.close();
        }
    });
</script>
