<script>
    jQuery('#ccsave_expiration').click('change',function() {
        var orginWidth = jQuery('.select-month').width();
        console.log(orginWidth);
        var a = jQuery('.select-month').width()-81;
        console.log(a);
        var result = -110 - a;
        jQuery('#advice-required-entry-ccsave_expiration_yr').css('left',result);
    });
</script>
<?php $_code = $this->getMethodCode() ?>
<script>
    function clearCcSave(){
        jQuery('#ccsave_cc_number_display').val('');
    }
    jQuery(function () {
        /*jQuery('input#_cc_owner').change(function(){
         name = jQuery(this).val();
         if (typeof defaultAddress !== 'undefined') {
         defaultAddress.firstname = name.substr(0,name.indexOf(' '))
         defaultAddress.lastname = name.substr(defaultAddress.firstname.length + 1);
         setAdd(defaultAddress);
         }
         });*/
        initSwipe('<?php echo $_code ?>');
        jQuery('select,input[type=radio],input[type=checkbox]').uniform({selectAutoWidth: false});
    });
</script>

<div class="paymentCC" id="payment_form_ccsave" style="display: none;">
    <label id="<?php echo $_code ?>-swiper-status" for="<?php echo $_code ?>swiper-data" onclick="clearInput();clearCcSave();"><?php echo $this->__("Click here to swipe") ?></label>
    <input type="text" style="height: 1px; width: 1px; border: 0 none; color: #FFF; font-size: 1px;"
           title="Swiper" class="input-text" id="<?php echo $_code ?>-swiper-data"
           name="<?php echo $_code ?>-swiper-data" value="    "/>

    <p><?php echo $this->__("Name on Card") ?> <span>*</span></p>
    <input type="text" width="238" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]"
           class="input-text required-entry"/>

    <p><?php echo $this->__("Credit Card Type") ?> <span>*</span></p>

    <div class="mySelect">
        <select name="payment[cc_type]" id="<?php echo $_code ?>_cc_type"
                class="required-entry validate-cc-type-select" style="width: 60%">
            <option value="">--<?php echo $this->__("Please Select") ?>--</option>
            <?php $_ccType = $this->getInfoData('cc_type'); ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option
                    value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <p><?php echo $this->__('Credit Card Number') ?> <span>*</span></p>
    <input type="text" id="<?php echo $_code ?>_cc_number_display"
           title="<?php echo $this->__('Credit Card Number') ?>"
           class="input-text" value=""/>
    <input type="hidden" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]"
           title="<?php echo $this->__('Credit Card Number') ?>"
           class="input-text validate-cc-number validate-cc-type" value=""/>

    <p><?php echo $this->__('Expiration Date') ?> <span>*</span></p>
<!--    <div>-->
    <div class="mySelect select-month" style="vertical-align: top">
        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]"
                class="validate-cc-ukss month">
            <?php foreach ($this->getCcMonths() as $k => $v): ?>
                <option
                    value="<?php echo $k ? $k : '' ?>"<?php if ($k == $this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div class="mySelect select-year" style="width: 60px;left: 25px;position: relative;">
        <select name="payment[cc_exp_year]" id="<?php echo $_code ?>_expiration_yr"
                class="year required-entry">
            <?php foreach ($this->getCcYears() as $k => $v): ?>
                <option
                    value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
            <?php endforeach ?>
        </select>
    </div>
<!--    <div style="" id="advice-required-entry-ccsave_expiration_yr" class="validation-advice"></div>-->

    <?php echo $this->getChildHtml() ?>
    <?php if ($this->hasVerification()): ?>
        <p><label for="<?php echo $_code ?>_cc_cid" class="required cc_verification "><?php echo $this->__('Card Verification Number') ?>
                <span>*</span></label></p>
        <div class="input-box">
            <div class="cc_save_fix v-fix" id="cc_save_fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>"
                       class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid"
                       name="payment[cc_cid]" value=""/>
            </div>
            <!--<a href="#" class="cvv-what-is-this"><?php /*echo $this->__('What is this?') */?></a>-->
        </div>
    <?php endif; ?>
    <?php if ($this->hasSsCardType()): ?>
        <li id="<?php echo $_code ?>_cc_type_ss_div">
            <ul class="inner-form">
                <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue"
                                            class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?>
                    </label></li>
                <li>
                    <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                    <span class="input-box">
                        <input type="text" title="<?php echo $this->__('Issue Number') ?>"
                               class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue"
                               name="payment[cc_ss_issue]" value=""/>
                    </span>
                </li>

                <li>
                    <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>

                    <div class="input-box">
                        <div class="v-fix">
                            <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]"
                                    class="validate-cc-ukss month">
                                <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                    <option
                                        value="<?php echo $k ? $k : '' ?>"<?php if ($k == $this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                        <div class="v-fix">
                            <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]"
                                    class="validate-cc-ukss year">
                                <?php foreach ($this->getSsStartYears() as $k => $v): ?>
                                    <option
                                        value="<?php echo $k ? $k : '' ?>"<?php if ($k == $this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </li>
                <li class="adv-container">&nbsp;</li>
            </ul>
            <script type="text/javascript">
                //<![CDATA[
                var SSChecked<?php echo $_code ?> = function () {
                    var elm = $('<?php echo $_code ?>_cc_type');
                    if (['SS', 'SM', 'SO'].indexOf(elm.value) != -1) {
                        $('<?php echo $_code ?>_cc_type_ss_div').show();
                    } else {
                        $('<?php echo $_code ?>_cc_type_ss_div').hide();
                    }
                };

                Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
                SSChecked<?php echo $_code ?>();
                //]]>
            </script>
        </li>
    <?php endif; ?>

</div>

<script type="text/javascript">

    function getStar(numberOfStar) {
        var str = '';
        for (var i = 0; i < numberOfStar; i++) {
            str = str + '*';
        }
        ;

        return str;
    }
    var currentValue = jQuery('#<?php echo $_code ?>_cc_number').val();

    function checkChange() {
        if (isOnline()) {
            if (jQuery('#magento_type').val() == "Enterprise") {
                if (jQuery('#store_credit_enable').val() == 1) {
                    if (jQuery('#store_credit_use').val() == 1) {
                        var balance = parseFloat(jQuery('#store_credit_balance').val());
                        var grand = jQuery('#grand_before').val();
                        var new_grand = grand.replace(',', '');
                        grand = parseFloat(new_grand).toFixed(2);
                        if (balance > grand) {
                            jQuery("#payment_method_hidden").val('free');
                            jQuery('#payment_detail').html('Store Credit');
                            updateTotals();
                            resizeTabbar();
                            return;
                        }
                    }
                }
            }
            var str = jQuery('#<?php echo $_code ?>_cc_number').val();
            if (str != undefined) {
                if (currentValue != str) {
                    str = str.replace(str.substr(2, 10), getStar(str.substr(2, 10).length));
                    jQuery('#<?php echo $_code ?>_cc_number_display').val(str);
                }
            }
        }
    }

    setInterval(checkChange, 2000);


    jQuery('#<?php echo $_code ?>_cc_number_display').change(function () {
        var str = jQuery(this).val();
        if (str.indexOf('*') < 0) {
            jQuery('#<?php echo $_code ?>_cc_number').val(str);
            str = str.replace(str.substr(2, 10), getStar(str.substr(2, 10).length));
            jQuery(this).val(str);
        }
    });
</script>


