<?php
    $_source = $this->getSource();
    $_order  = $this->getOrder();
?>
<?php if ($_source->getCreditTotalRefunded()): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo Mage::helper('credit')->__('Refunded to Store Credit'); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>><?php echo $_order->formatPrice($_source->getCreditTotalRefunded()) ?></td>
</tr>
<?php endif ?>
