<?php
/**
 * Created by PhpStorm.
 * User: vjcspy
 * Date: 6/24/15
 * Time: 2:19 PM
 */
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<!--<meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" name="viewport">-->
<meta name="HandheldFriendly" content="true">

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />

<title><?php /*echo htmlspecialchars(html_entity_decode($this->getTitle())) */?></title>
<title>X-POS</title>
<!--<link rel="icon" href="--><?php //echo $this->getSkinUrl('favicon.ico') ?><!--" type="image/x-icon"/>z-->
<!--<link rel="shortcut icon" href="--><?php //echo $this->getSkinUrl('favicon.ico') ?><!--" type="image/x-icon"/>-->

<?php echo $this->getCssJsHtml() ?>
<?php //echo $this->helper('core/js')->getTranslatorScript() ?>
<?php //echo $this->getChildHtml('calendar'); ?>
<?php //echo $this->getChildHtml('optional_zip_countries'); ?>

<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
    var BLANK_IMG = '<?php echo $this->getJsUrl() ?>spacer.gif';
    var BASE_URL = '<?php echo $this->getUrl('*', array('_nosid' => true)) ?>';
    var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';
    var FORM_KEY = '<?php echo $this->getFormKey() ?>';

</script>

