<?php
require_once(Mage::getModuleDir('controllers', 'Mage_Adminhtml') . DS . 'Sales' . DS . 'Order' . DS . 'CreditmemoController.php');

/**
 * Created by PhpStorm.
 * User: vjcspy
 * Date: 7/18/15
 * Time: 10:43 PM
 */
class SM_XPos_Adminhtml_Sales_Order_CreditmemoController extends Mage_Adminhtml_Sales_Order_CreditmemoController
{
    /**
     * Initialize creditmemo model instance
     *
     * @return Mage_Sales_Model_Order_Creditmemo
     */
    protected function _initCreditmemo($update = false)
    {

        $creditmemo = parent::_initCreditmemo($update); // TODO: Change the autogenerated stub
        foreach ($creditmemo->getAllItems() as $creditmemoItem) {
            $orderItem = $creditmemoItem->getOrderItem();
            $parentId = $orderItem->getParentItemId();
            if (isset($backToStock[ $orderItem->getId() ])) {
                $productId = $creditmemoItem->getData('product_id');
                Mage::helper('xpos/realTimeProduct')->proNeedReload($productId, null);
            } elseif ($orderItem->getParentItem() && isset($backToStock[ $parentId ]) && $backToStock[ $parentId ]) {
                $productId = $creditmemoItem->getData('product_id');
                Mage::helper('xpos/realTimeProduct')->proNeedReload($productId, null);
            } elseif (empty($savedData)) {
                $productId = $creditmemoItem->getData('product_id');
                Mage::helper('xpos/realTimeProduct')->proNeedReload($productId, null);
            } else {
                $creditmemoItem->setBackToStock(false);
            }
        }

        return $creditmemo;
    }


}
