<?php

/**
 * Created by PhpStorm.
 * User: vjcspy
 * Date: 7/14/15
 * Time: 4:28 PM
 */
class SM_XPos_Model_Adminhtml_System_Config_Backend_LastSaveSetting extends Mage_Core_Model_Config_Data
{
    /**
     * Processing object after save data
     *
     * @return Mage_Core_Model_Abstract
     */
    protected function _afterSave()
    {
        $currentAdmin = Mage::getModel('xpos/iayz')->getCurrentAdmin();
        $currentAdminUserName = $currentAdmin['userName'];
        $currentTime = Mage::getModel('core/date')->date('Y-m-d H:i:s');
        $config = new Mage_Core_Model_Config();
        $result = $currentAdminUserName . ' at ' . $currentTime;
        $config->saveConfig('xpos/general/last_save_setting', $result);

        return parent::_afterSave(); // TODO: Change the autogenerated stub
    }

    protected function _beforeSave()
    {
        return parent::_beforeSave();
    }

    public function save()
    {
        return parent::save();
    }

}

