<?php
$_balance = $this->getBalance();
?>

<div class="fieldset">
    <h2 class="legend"><?php echo Mage::helper('credit')->__('Balance') ?></h2>
    <div>
        <table width="100%">
            <tr>
                <td width="50%">
                    <?php echo Mage::helper('credit')->__('Your current balance is: <b>%s</b>', 
                        Mage::helper('core')->currency($_balance->getAmount())) ?>
                </td>
                <td width="50%" style="text-align: right;">
                    <form action="<?php echo Mage::getUrl('credit/account/subscribe') ?>" method="post" id="form-validate">
                        <div>
                            <input type="checkbox" id="credit_subscription" class="checkbox" name="is_subscribed" value="1"
                                <?php if ($_balance->getIsSubscribed()): ?>checked="checked"<?php endif ?>>

                            <label for="credit_subscription">
                                <?php echo Mage::helper('credit')->__('Subscribe to email notifications') ?>
                            </label>

                            &nbsp;&nbsp;
                            <button type="submit" class="button">
                                <span><span>
                                    <?php echo Mage::helper('credit')->__('Save') ?>
                                </span></span>
                            </button>
                        </div>
                    </form>
                </td>
            </tr>
        </table>
    </div>
</div>