<?php
/* * ************************************************
 * Name: Admin theme
 * Author: The Cmsmart Development Team 
 * Websites: http://cmsmart.net
 * Technical Support: Forum - http://cmsmart.net/support
 * GNU General Public License v3 (http://opensource.org/licenses/GPL-3.0)
 * Copyright © 2011-2013 Cmsmart.net. All Rights Reserved.
 * ************************************************* */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<script>
jQuery(function($) {
	$('.nav-bar1 ul#nav').attr('id', 'accordion');
	if ($(window).width() < 600 )
	{
		$('.adminhtml-dashboard-index fieldset tbody tr').attr('title', '');
		$('.adminhtml-dashboard-index #grid_tab_content tbody tr').attr('title', '');
		
	}
        <?php if($this->getRequest()->getControllerName() != 'xpos'){ ?>
	$('#accordion').accordion();
        <?php } ?>
	var wh = $( '.wrapper' ).height();
	$('#accordion').css('min-height', wh);
	jQuery('#nbclick1').click(function() {

		var effect = 'slide';
		   // Set the options for the effect type chosen
		   var options = { direction: 'left' };
		   // Set the duration (default: 400 milliseconds)
		   var duration = 700;	 
		   $('.nb-navbar1').toggle(effect, options, duration);			   
		});	
jQuery('#nbclick').click(function() {
	var effect = 'slide';
	   // Set the options for the effect type chosen
	   var options = { direction: 'left' };
	   // Set the duration (default: 400 milliseconds)
	   var duration = 700;	 
	   $('.nav-bar1').toggle(effect, options, duration);
	
	});

});

</script>
<body id="html-body"<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : ''; ?>>
<?php echo $this->getChildHtml('notification_window'); ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
        <div class="header">
            <?php echo $this->getChildHtml('header') ?>
        <div class="clear"></div>
            <?php echo $this->getChildHtml('menu') ?>
        </div>
        
        <?php echo $this->getChildHtml('notifications'); ?>
        <div class="middle" id="anchor-content">
            <div id="page:main-container">
            <?php if($this->getChildHtml('left')): ?>
                <div class="columns <?php echo $this->getContainerCssClass() ?>">
                    <div class="side-col" id="page:left">
                        <?php echo $this->getChildHtml('left') ?>
                    </div>
                    <div class="main-col" id="content">
                        <div class="main-col-inner">
                            <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
                            <?php echo $this->getChildHtml('content') ?>
                        </div>
                    </div>
                </div>

            <?php else: ?>
                <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
                <?php echo $this->getChildHtml('content') ?>
            <?php endif; ?>
            </div>
        </div>
        <div class="footer">
            <?php echo $this->getChildHtml('footer') ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('js') ?>
    <?php echo $this->getChildHtml('profiler') ?>
<div id="loading-mask" style="display:none">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>"/><br/><?php echo Mage::helper('adminhtml')->__('Please wait...') ?></p>
</div>

<?php echo $this->getChildHtml('before_body_end') ?>

</body>
</html>
