<?php
/**
 * Created by PhpStorm.
 * User: vjcspy
 * Date: 6/25/15
 * Time: 6:09 PM
 */ 
class SM_XPos_Model_Tax_Calculation extends Mage_Tax_Model_Calculation {
    public static $_getFromXpos = false;
    public function getRateRequest(
        $shippingAddress = null,
        $billingAddress = null,
        $customerTaxClass = null,
        $store = null)
    {
        if($this::$_getFromXpos == false) {
            $request = parent::getRateRequest($shippingAddress, $billingAddress, $customerTaxClass, $store); // TODO: Change the autogenerated stub
        }else{
            $request = parent::getRateRequest($shippingAddress, $billingAddress, $customerTaxClass, $store); // TODO: Change the autogenerated stub
            $request->setCustomerClassId($customerTaxClass);
        }
        $this::$_getFromXpos = false;
        return $request;
    }


}
