<?php
/**
 * Created by PhpStorm.
 * User: Smartor
 * Date: 11/14/14
 * Time: 10:39 AM
 */
 if($this->canDisplayGiftmessage()): ?>
    <?php $_required = $this->getMessage()->getMessage() != ''?>
    <div id="<?php echo $this->getHtmlId() ?>" class="box-left giftmessage-whole-order-container" style="width: 95%">
        <div class="entry-edit">
            <div><?php echo Mage::helper('sales')->__('Gift Message for the Entire Order') ?></div><br />
            <form id="<?php echo $this->getFieldId('form') ?>" action="<?php echo $this->getSaveUrl() ?>">
                <fieldset>
                    <input type="hidden" id="<?php echo $this->getFieldId('type') ?>" name="<?php echo $this->getFieldName('type') ?>" value="order" />
                    <table width="95%" cellspacing="0">
                        <tbody>
                        <tr>
                            <td class="label" style="vertical-align: middle;"><label><?php echo Mage::helper('sales')->__('From Name') ?><?php echo $_required ? '&nbsp;<span class="required">*</span>' : ''?></label></td>
                            <td class="input-ele"><input class="input-text" type="text" id="<?php echo $this->getFieldId('sender') ?>" name="<?php echo $this->getFieldName('sender') ?>" value="<?php echo $this->escapeHtml($this->getMessage()->getSender()) ?>" /></td>
                            <td>&nbsp;</td>
                            <td class="label" style="vertical-align: middle;"><label><?php echo Mage::helper('sales')->__('To Name') ?><?php echo $_required ? '&nbsp;<span class="required">*</span>' : ''?></label></td>
                            <td class="input-ele"><input style="width: 95%" class="input-text" type="text" id="<?php echo $this->getFieldId('recipient') ?>" name="<?php echo $this->getFieldName('recipient') ?>"  value="<?php echo $this->escapeHtml($this->getMessage()->getRecipient()) ?>" /></td>
                        </tr>
                        <tr>
                            <td class="label" colspan="6"><label for="<?php echo $this->getFieldId('message') ?>"><?php echo Mage::helper('sales')->__('Gift Message') ?></label></td>
                        </tr>
                        <tr>
                            <td style="width: 95%" colspan="5"><textarea style="height:6em;width: 98%" id="<?php echo $this->getFieldId('message') ?>" name="<?php echo $this->getFieldName('message') ?>" rows="2" cols="77"><?php echo $this->escapeHtml($this->getMessage()->getMessage()) ?></textarea></td>
                        </tr>
                        <tr>
                            <td colspan="5" class="a-right" style="padding-top:5px;padding-right: 15px"><span id = "save_mess" ><?php echo $this->getSaveButtonHtml(); ?></span></td>
                        </tr>
                        </tbody>
                    </table>
                </fieldset>
            </form>
        </div>
    </div>
<?php endif ?>
<script>
    jQuery('#save_mess').click(function(){
        alert('Message Saved !')
    });
</script>